### ISSUE TITLE
Missing  example for internal linking

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#103]
Documentation issue

**Comment by racke** [comment]
Named anchors lacks an example for "Instead a text-amuse-label prefix is added (if you need to link it externally). ". Need to know how the external link should look like.

**Comment by melmothx** [comment]
Actually, this is not a documentation issue, as looking up a way to construct an url looks like labour anyway. So:

 1. Complete the support for named anchors in Text::Amuse, including chapter/section, and add a class to the HTML output.

 2. Here, add js to show an icon flag on the left margin, on which you can click and copy the link location.

**Comment by racke** [comment]
:+1:

**Comment by melmothx** [comment]
https://github.com/melmothx/text-amuse-compile/commit/47c1c6fa93a3774e7257f043ea12317f8865d1de

The compiler as well needs upgrade
