### ISSUE TITLE
Article output

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#104]
When high level sectioning is used, there should be an option to output an article style.

HTML has no knowledge of chapter, sections, etc.

**Comment by melmothx** [comment]
Still unclear at which level this should be handled.

**Comment by melmothx** [comment]
This should be done in Text::Amuse::Compile adding an option.

Set the class to scrartcl and do `\let\chapter\section  \let\part\section` (or something smarter). However, to prevent global explosion, it would be important to leave the main latex body untouched.

**Comment by melmothx** [comment]
[manual.pdf](https://github.com/melmothx/amusewiki/files/901773/manual.pdf)

Sample compiled with notoc and nocoverpage

**Comment by racke** [comment]
Works for me, but wouldn't it be more consistent to leave out HTML toc as well in case notoc is set?

**Comment by melmothx** [comment]
That's a good point
