### ISSUE TITLE
Blank lines in visual editor

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#11]
Original report

When a text is added through the visual editor there are some (4,
maybe) trailing "\n" (enters, new lines). I expected only one or none
at all.

**Comment by melmothx** [comment]
This depends on the input HTML.

Generally speaking, the muse format doesn't care how many empty lines
you have, it will just count as 1.

Anyway, the HTML => muse parser preserves the invisible non-breaking
spaces found in the input on a paragraph by themselves, because
usually they mean that the original author wanted some more space.

If the input is broken and it's abusing the NBSP you get a broken
text, of course.

**Comment by tinglado** [comment]
Maybe you're right but if you put "Hello world" in the visual editor, then you got four extra lines in the source text editor as in more complex HTML. Then, if those lines are removed and you preview or submit the text, only one new line is created which is fine.

**Comment by melmothx** [comment]
tinglado <notifications@github.com> writes:

> Maybe you're right but if you put "Hello world" in the visual editor,
> then you got four extra lines in the source text editor as in more
> complex HTML. Then, if those lines are removed and you preview or
> submit the text, only one new line is created which is fine.

Ok, I see, but this is not at all an issue. Blank lines are totally
irrelevant, they have no effect on the output. Also, they are just
leading and trailing on the body, as far as I can see. Two paragraphs
with Hello world will give back:

#header
=line=
=line=
=line=
Hello world
=line=
Hello there
=line=
=line=
=line=
=line=

Which is fine. Is that creating issues?

**Comment by melmothx** [comment]
Actually, there is a reason for leading and trailing newlines. Basically paranoia.

As already stated elsewhere, 1 or 100 newlines are all threated the
same. *But* having missing newlines between the body and the header,
could be nasty. Also I don't like having text files without a trailing
newlines is not something I like to have around. So I choose to play
on the safe side.

Closing this issue, as it not an issue. Thanks for the report :-)
