### ISSUE TITLE
Compilation error when striked text in title

### ISSUE THREAD

**Issue by Karmak23** [melmothx/amusewiki#113]
When writing this in document :

```
* Write a title with something <strike>not politically correct</strike> err… politically correct
```
Compilation of `TeX` file fails.

In the code, this leads to :

```
\part{Anti-thèses en faveur \sout{d’un empalement sauvage du\dots{}} pardon, d’un cantonnement à l’imaginaire de ce cher monsieur appelé « Père Noël »}
```

Removing the `<strike> </strike>` solves the issue, and compilation succeeds.

Any thoughts on why ?

I've not the compilation log anymore now that the problem is gone, but I can generate it again if you're interested.

**Comment by melmothx** [comment]
Wrapper needed because of hyperref.

https://tex.stackexchange.com/questions/22410/strikethrough-in-section-title

**Comment by Karmak23** [comment]
I love you, man :-D

**Comment by melmothx** [comment]
Fix is found and new Text::Amuse::Compile is upcoming. Upgrading the module will be enough. New package will be available shortly.

**Comment by melmothx** [comment]
Package available on http://packages.amusewiki.org/ and released on CPAN.

**Comment by Karmak23** [comment]
works like a charm. Thanks !
