### ISSUE TITLE
Please add backlinks

### ISSUE THREAD

**Issue by lichtkind** [melmothx/amusewiki#118]
I mean basically the functionality of https://en.wikipedia.org/wiki/Special:WhatLinksHere/Main_Page, a listing of pages that reference to the current page. It would be even nicer if its an pop up menu so I can access it with a "long click". Because often there are no back links that interest me. So I don't have to return from the back links page to page to the current by pressing back button on browser.

Thanks

**Comment by melmothx** [comment]
Please take a look here and please let me know if adjustments are needed. Feel free to create cross-linked texts, the site is open for editing and publishing.

https://staging.amusewiki.org/library/bookbuilder-tutorial
