### ISSUE TITLE
Do not use "pt" in EPUB CSS

### ISSUE THREAD

**Issue by labdsf** [melmothx/amusewiki#122]
When "pt" units are used for font sizes, they don't scale in FBReader when I change base font size. "Zoom in" and "zoom out" just change the base font size, but "pt"s are not relative units. Size changes only if I configure FBReader to ignore CSS or remove `stylesheet.css` form EPUB archive.

For example, points are used here:
https://github.com/melmothx/amusewiki/blob/c4a528d86c83692984df3be3b7140f4ea936cbbf/t/custom-templates/css.tt#L42

This line can be changed to

    [% IF webfonts %][% webfonts.size %]pt[% ELSE %]1em[% END %]

This is the easy way to avoid converting `webfonts.size` to em's.

I suggest to change "body" size to "1em", so fonts do not change when reader switches between amusewiki books and books without styles, and adjust other font sizes accordingly. For example, `sub` and `sup` elements, which now have font size of 8pt (which does not even depend on `webfonts.size` option, so everyone will benefit from using relative sizes), will have size of 0.8em etc.

**Comment by melmothx** [comment]
Hi and thanks for this.

Here there are two different issues.

The first is the CSS which has some hardcoded values in pt, so yes, this needs to be fixed.

The second is the pt size in the base font. I'm going with use the pt size when the fonts are embedded in the epub.

**Comment by melmothx** [comment]
@labdsf Please take a look at the samples attached here and to the commit and let me know if it makes sense to you.

[samples.zip](https://github.com/melmothx/amusewiki/files/1185632/samples.zip)

**Comment by melmothx** [comment]
Tested on FBreader and the default EPUB zooms correctly.

**Comment by melmothx** [comment]
Anyway, embedded or not, I start to believe that setting the size at all in CSS is a mistake. Thought?

**Comment by labdsf** [comment]
`manual-no-embed.epub` scales, but `manual-embedded.epub` does not (because of `12pt` on `html` and `body`).

> Tested on FBreader and the default EPUB zooms correctly.

I am testing on Android FBreader 2.1 (latest version from F-droid, somewhat old), but last time I tested on Google Play version, FBreader did not scale `pt` sizes. Desktop FBreader scales both samples and does not load embedded fonts (apparently, it does not support `@font-face`) so there is no visual difference.

> Anyway, embedded or not, I start to believe that setting the size at all in CSS is a mistake. Thoughts?

I am not sure what is the reason for embedded fonts version. If it is a way to create a "printer-friendly" version of EPUB that will print the same regardless of who prints it (better use PDF though), then setting absolute font sizes makes sense. If not, it is better to make more fine-grain settings, with "embed fonts" meaning "embed fonts and do nothing else".

**Comment by melmothx** [comment]
Alexander Krotov <notifications@github.com> writes:

> `manual-no-embed.epub` scales, but `manual-embedded.epub` does not (because of `12pt` on `html` and `body`).

Yes, correct.

>> Anyway, embedded or not, I start to believe that setting the size at all in CSS is a mistake. Thoughts?
>
> I am not sure what is the reason for embedded fonts version. If it is a way to create a "printer-friendly" version of EPUB that will print the same regardless of who prints it (better use PDF though), then setting absolute font sizes makes sense. If not, it is better to make more fine-grain settings, with "embed fonts" meaning "embed fonts and do nothing else".

I assume "embedded fonts version" means "embedded fonts size" (as having
the fonts embedded in the EPUB is useful).

EPUB is not meant to be printed. At least I'm not aware of an
application which prints them. So it should be considered a mobile-only
thing.

So, I'm going to ignore the font size in CSS and hide the option from
the Bookbuilder on amusewiki (which is the only point where the fonts
are embedded).

Thanks for your help.

-- 
Marco
