### ISSUE TITLE
Old EPUBs use old CSS

### ISSUE THREAD

**Issue by labdsf** [melmothx/amusewiki#131]
Since #122 is fixed, all new books have correct CSS and fonts scale correctly. But all books generated previously still have CSS with fonts specified in points. Is it possible to rebuild all books? I checked, [upgrade manual](https://amusewiki.org/library/upgrade-amusewiki) does not say anything about it.

**Comment by melmothx** [comment]
Well, considering that some sites are really large, and on slow machines could take even a day to rebuild the files (please note: the time consumed it mostly spent in LaTeX runs), it doesn't seem a good idea to automatically rebuild everything on each change (unless there's a regression which needs urgent fix).

However, the option to rebuild everything does exist for admin users, under `/tasks/rebuild`, and also the option to rebuild just a single text is present in the box with the downloads (beside the bookbuilder, IIRC accessible to all librarians). If it's not a site you administer, please contact the admins to do some button pushing. The rebuilding is async (split in jobs with very low priority) so it doesn't affect the normal functioning of the site.
