### ISSUE TITLE
Selecting chapters for the bookbuilder

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#14]
No, it's not possible, at least not right now. This is more complicated
that you may think, because it's unclear where a chapter starts and
where finishes, how the user is supposed to select it and so on.

An alternate approach could be for the user to copy and paste from the
sources (the .muse file) the interesting chapters into the sandbox and
from there publish and recompile.

Maybe it would be possible to create a in-site sandbox for this purpose

**Comment by tinglado** [comment]
I had the same request from other people. With the alternate approach do you mean that the extracted text would be visible for others and there are no option to do that "private"? I mean, if you publish a chapter in a separate entry, that entry would be publish in the rss too. Am I right?

**Comment by melmothx** [comment]
tinglado <notifications@github.com> writes:

> I had the same request from other people. With the alternate approach
> do you mean that the extracted text would be visible for others and
> there are no option to do that "private"? I mean, if you publish a
> chapter in a separate entry, that entry would be publish in the rss
> too. Am I right?

If you publish a chapter in a separate entry, you of course get a
regular text, so it will be present in the listings, RSS, etc.

The alternate approach would be something a bookbuilder working on a
direct user input. So the user pastes the stuff in a text area, set the
options, recompile. Usually the output stays there (with no listing) for
a month.

Would that work for you?

-- 
Marco

**Comment by melmothx** [comment]
Maybe it would even somehow pulling the texts automatically and then let the user cut the parts s/he's not interested in. Just to alleviate the cut&paste labor.

**Comment by tinglado** [comment]
Ok, I understand now. The main issue for me is that there are some users with little knowledge of how things work, so using the sources often is not an option. Maybe a tutorial could be a good idea but still I see the tech barriers for some people. The bookbuilder UI seems to address many of those barriers in a good way. It would be good to have a simpler solution but honestly it's difficult even imagine one because other problems arise and I'm not considering some technical difficulties that you describe in the first message.

This is not critical for me, and the sandbox for the bookbuilder could help to mantain the rss clean.

**Comment by melmothx** [comment]
tinglado <notifications@github.com> writes:

> Ok, I understand now. The main issue for me is that there are some
> users with little knowledge of how things work, so using the sources
> often is not an option. Maybe a tutorial could be a good idea but
> still I see the tech barriers for some people. The bookbuilder UI
> seems to address many of those barriers in a good way. It would be
> good to have a simpler solution but honestly it's difficult even
> imagine one because other problems arise and I'm not considering some
> technical difficulties that you describe in the first message.
>
> This is not critical for me, and the sandbox for the bookbuilder could
> help to mantain the rss clean.

Of course the problem is not just the RSS, it's the amount of duplicated
things you will stuff into the archive, which just add noise.

Give me some time to think about something, this is not a trivial thing.

Could you estimate how heavily this thing would be used? I mean, here we
have to understand if the feature is worth the pain it generates or not.

Also, it would help to visualize the process. How the user would be
supposed to mark the chapters/pieces, without resorting to copy and
paste into a text area, which is a pain to work with in any case. (I use
the firefox plugin "It's all text" if I need to do editing into the
browser).

-- 
Marco

**Comment by melmothx** [comment]
@tinglado

> Ok, I see some noise, but if you delete the text after you create the output
> that you wish, the only thing that create noise would be the git repository
> or there are other parts that would be affected? Just a curious question,

Well, yes, the git repository history would be full of useless noise,
with additions and deletions. Ok, basically not an issue per se, but
hell, if can be done better, better do it so.

> Yes, the first thing that come into my head it is to put a "+" button
> (as the bookbuilder) in every entry of the index (or as a check box),
> but this could be much. It should be necessary to establish a limit for
> adding chapters? Let's say if you have sub-sub-sections it could become
> a mess to make something that can handle that. On the other hand it would
> be great to do something flexible that allow the minimum "part" of a book
> (thinking in sections or subsections from compilations that have a ton of
> small texts). I doesn't have a strong opinion on anything on this topic so
> if I have a better idea I will add it here in the future.

Ok, still mumbling.

**Comment by melmothx** [comment]
Ok, plan for this:

 - provide a as_splat_latex method in Text::Amuse

 - add support for partials in Text::Amuse::Compile
   probabily the form filename:1,11,12,20 will do without having to
   pass structures too deep

 - create a route like /library/text/select, which will display a
   table where each left cell is a fragment (in html, using the
   existing as_splat_html method), while in the right cell there is
   going to be a checkbox. @tinglado I think this would work, right?

 - that will post to the the bookbuilder with the filename and the
   selected fragments.

 - Text::Amuse::Compile is going to take care of the rest.
