### ISSUE TITLE
Support sending text in post and render them 

### ISSUE THREAD

**Issue by yodatak** [melmothx/amusewiki#158]
Any way to implement this , like posting the html or event a URL 

Maybe like this ?
'It would be something like POSTing to an url the parameters with the HTML text and the various attributes like title/subtitle, together with __username and __password, create the revision and schedule its publishing, returning the (expected) text url. It would not appear right away (because of the async publishing), but shortly enough and will work just fine.' melmothx

**Comment by melmothx** [comment]
Yes, that's totally doable and will be done soon.

**Comment by melmothx** [comment]
This is done but needs proper documentation, so letting it open.

**Comment by melmothx** [comment]
Documented here

**Comment by melmothx** [comment]
https://amusewiki.org/library/integration-with-external-sites
