### ISSUE TITLE
Use the URL to create the post on the wiki

### ISSUE THREAD

**Issue by yodatak** [melmothx/amusewiki#159]
Like many website to markdown online convert does or even the wallabag does convert the site to the readable format and then provide the epub ,  it can be useful to make more post on the wiki

**Comment by melmothx** [comment]
The conversion to the markup is already there (not bound to any text). See `/utils/import`

I've thought a while ago by an "Import from url" utility, but at the end I resolved not to, as it potentially open a whole can of worms security-wise. Plus usually the sites on the internet have a lot of layout elements which will just turn to crap, so a manual intervention is very much needed anyway. 

Bottom line: not worth the effort and the troubles attached to this. Closing this.
