### ISSUE TITLE
Browser crashes handling big texts

### ISSUE THREAD

**Issue by tinglado** [melmothx/amusewiki#16]
Using Tor Browser with different versions thw browser crash in some cases when I cut or paste the entire text (~200 pages in A5 for example) in the sandbox or in the visual editor. Currently I run Tor Browser 5.0.3 (based on Firefox 38.3.0) and I couldn't test this in other browsers (sorry about that).

Sometimes pasting ~50 pages in the visual editor crash the browser.

Maybe this has nothing to do with amusewiki itself, but I report it to know if there are other solution or I need to paste an entire text in several parts.

**Comment by melmothx** [comment]
tinglado <notifications@github.com> writes:

> Using Tor Browser with different versions thw browser crash in some
> cases when I cut or paste the entire text (~200 pages in A5 for
> example) in the sandbox or in the visual editor. Currently I run Tor
> Browser 5.0.3 (based on Firefox 38.3.0) and I couldn't test this in
> other browsers (sorry about that).
>
> Sometimes pasting ~50 pages in the visual editor crash the browser.
>
> Maybe this has nothing to do with amusewiki itself, but I report it to
> know if there are other solution or I need to paste an entire text in
> several parts.

It looks like a browser/machine issue. Considering how fat these
browsers are, it wouldn't surprise me that it goes out of memory
handling the JS stuff of the visual editor. Have you any dmesg log about
the crash?

**Comment by melmothx** [comment]
Actually, I think it's doable to provide a text box with an url of an internet page and fetch that one. Or a file upload with an HTML page and process that. Keep in mind that will be a lot of stuff to clean afterward in the source editor.

**Comment by melmothx** [comment]
@tinglado

> The memory is the error. I don't have logs but I can see how the browser
> eat the ram memory and then the swap memory from my machine while it's
> "loading". The file upload through HTML would be good enough. The fetch from
> an url would apply only for simple cases where a text is all in the html or
> also in more complex "environments" as fetching from a blog?

ok, that's because the JS for that stuff is really heavy. Fetching a
blog would load a ton of crap you will have to delete away. May or may
be not be useful.

Let's go with file upload.

**Comment by melmothx** [comment]
I started to implement url upload, but turned out is a bit tricky security wise (requests to localhost, file:///, etc.).
