### ISSUE TITLE
Any way to have custom fonts for title or every H1,H2

### ISSUE THREAD

**Issue by yodatak** [melmothx/amusewiki#161]
i can be useful to custom the rending to have a custom font support for styling render in the pdf rending.

**Comment by melmothx** [comment]
In the upcoming release you can choose to use sans font for titles (and choose the sans font). Now with a modified fontspec.json you can define an arbitrary font as sans and use it for titling.

I think here we're missing a bit of documentation, so leaving this open until it's properly documented.

**Comment by melmothx** [comment]
Documented at https://amusewiki.org/library/custom-fonts
