### ISSUE TITLE
Amusewiki name

### ISSUE THREAD

**Issue by noraj1337** [melmothx/amusewiki#166]
**Amusewiki** seems to be the new name of **AmuseWikiFarm**. So either this is true and the [README](https://github.com/melmothx/amusewiki/blob/master/README) and packages need an update. Either i'm wrong and a clarification is needed because the difference between Amusewiki and AmuseWikiFarm is not obvious.

**Comment by melmothx** [comment]
Thanks for bringing this issue to my attention, I've corrected the
README, which is indeed confusing.

This engine is the rewriting of an earlier amusewiki which I was
developing years ago, which used the AmuseWiki namespace and got
superseded by this one, keeping the good ideas and dropping the bad
ones. Notably, the old software didn't scale for multisite, hence the
"Farm" suffix in the namespace.

Currently it's truly out of question to rename all the
modules/scripts/testfiles for a (mostly) cosmetic reason.

At any rate, the modules are for the programmers' (hopefully
forgiving) eyes only. Everywhere else the softwre is referred to (and
always was) as "amusewiki", with random capitalization.

I hope this clears out the matter. Please close the issue if you think
commit 68d0027 is enough to address it.

**Comment by noraj1337** [comment]
Ok, this is right.
