### ISSUE TITLE
Make a atom language for Text::Amuse

### ISSUE THREAD

**Issue by yodatak** [melmothx/amusewiki#176]
It could be cool if a language package is created for coloration in atom any people know how to do it ?

**Comment by labdsf** [comment]
I don't use Atom, but you can find multiple discussions on https://discuss.atom.io/t/documentation-for-creating-custom-grammars/20459/2

There is a syntax highlighting package for Emacs, you can borrow some regular expressions here:
https://github.com/melmothx/text-amuse/blob/6232e6c1fb261ccd544803b5d867d52594c79237/examples/text-amuse-mode.el

**Comment by link2xt** [comment]
I have started [a repo](https://github.com/link2xt/atom-muse) Package is published as [atom-muse](https://atom.io/packages/atom-muse) and can be installed already.

It handles some basic markup, like emphasis and headers.

**Comment by melmothx** [comment]
Advertised on the amusewiki.org front-age. Thanks @link2xt  !

**Comment by link2xt** [comment]
@yodatak Check Atom package [language-muse](https://atom.io/packages/language-muse) if you are still interested. Atom package already highlights most of the markup manual. List markers and nested emphasis tags are not highlighted yet, but there are no obvious huge bugs.

I think the issue can be closed.

**Comment by melmothx** [comment]
Thanks @link2xt, closing this.

**Comment by yodatak** [comment]
Thanks its works !

**Comment by link2xt** [comment]
There is another implementation of Muse grammar by @Alhadis in https://github.com/Alhadis/language-emacs-lisp now.

[https://atom.io/packages/language-emacs-lisp](language-emacs-lisp) package is going to provide Muse support, and it is [already more complete](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-emacs-lisp%2Fblob%2Fmaster%2Fgrammars%2Fmuse.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmelmothx%2Famusewiki-site%2Fblob%2Fmaster%2Fm%2Fml%2Fmanual.muse&code=) than my implementation.

@yodatak You might want switch to it instead once it is released.

@melmothx It makes sense to advertise this one on the homepage as well. These efforts also going to result in syntax highlighting support on GitHub soon.

**Comment by melmothx** [comment]
@link2xt sure, please feel free to do so. Way better if you describe the situation than me rewording what you said. Thanks!

**Comment by Alhadis** [comment]
Just a sidenote: `language-emacs-lisp` is also what's powering Elisp highlighting across GitHub.com (which is the whole reason I wrote it in the first place).

So if you see any highlighting errors with Emacs Lisp code, let me know there too. =)
