### ISSUE TITLE
Generate single configuration file for nginx

### ISSUE THREAD

**Issue by link2xt** [melmothx/amusewiki#179]
What is the reason to generate `amusewiki_include` and immediately include it in `amusewiki`? Why not just generate single `amusewiki` with embedded `amusewiki_include`?

**Comment by melmothx** [comment]
IIRC, this way changes are better tracked if you have something like etckeeper or just /etc/nginx under git. I.E. it's clearer what changed, and also visually clear that the information is just repeated over and over.

Now, true that the conf looks pretty stable. However, as you latest PR, in etc would generate more diff noise if we had a single configuration file.

I do not have a strong opinion on this matter. At the time it made sense this way. Right now... unclear

**Comment by melmothx** [comment]
> IIRC, this way changes are better tracked if you have something like etckeeper or just /etc/nginx under git. I.E. it's clearer what changed, and also visually clear that the information is just repeated over and over.
> 
> Now, true that the conf looks pretty stable. However, as you latest PR, in etc would generate more diff noise if we had a single configuration file.
> 
> I do not have a strong opinion on this matter. At the time it made sense this way. Right now... unclear

@link2xt is this explanation making  sense and this issue can be closed?

**Comment by link2xt** [comment]
Ok, let's close it.
