### ISSUE TITLE
Requirement for "Please describe shortly what you did" on preview

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#2]
This doesn't make sense to enforce in my opinion. Even requiring it at all might be to annoying for the regular user :-).

**Comment by melmothx** [comment]
"Stefan Hornburg (Racke)" <notifications@github.com> writes:

> This doesn't make sense to enforce in my opinion. Even requiring it at
> all might be to annoying for the regular user :-).

Do you think the problem is in the enforcing itself or just because it's
triggered on preview as well?

-- 
Marco

**Comment by racke** [comment]
Well I would say the general behaviour should be configurable (required / optional), but
triggering it on preview is definitely disruptive and should be fixed.

**Comment by melmothx** [comment]
"Stefan Hornburg (Racke)" <notifications@github.com> writes:

> Well I would say the general behaviour should be configurable
> (required / optional), but
> triggering it on preview is definitely disruptive and should be fixed.

Agreed, thanks for reporting. It will be fixed soon.

-- 
Marco

**Comment by melmothx** [comment]
I believe the thing is fixed. Thanks for the report!
