### ISSUE TITLE
Cheatsheet: make "code" more prominent

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#22]

**Comment by racke** [comment]
Also if you see <example>XXX</example> just treat it like <code>XXX</code>.

**Comment by melmothx** [comment]
turn <example>XXX</example> to <code>XXX</code> (inline)

**Comment by melmothx** [comment]
example => code when is inlined

**Comment by melmothx** [comment]
make the "one or more leading whitespace" *bold* in the list doc

**Comment by melmothx** [comment]
The parsing improvement belongs to other repo. Closing here and thanks for the report.
