### ISSUE TITLE
The difference between "tasks/all/show" and "admin/jobs/show" is not clear

### ISSUE THREAD

**Issue by link2xt** [melmothx/amusewiki#232]
There are two items: "Job status" and "Jobs" in the menu. "Jobs" (`admin/jobs/show`) is only available to "root" role, but how is it different from "Job status" (`tasks/all/show`), which is available to admin?

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> There are two items: "Job status" and "Jobs" in the menu. "Jobs" (admin/jobs/show) is only available
> to "root" role, but how is it different from "Job status" (tasks/all/show), which is available to
> admin?

The label is indeed a bit confusing, indeed. The /admin route shows all
the jobs for all the sites, while the /tasks/ is for the current site
only. Root users are cross site without the need to belong to them.

--
Marco

**Comment by link2xt** [comment]
Maybe rename them to something like "Jobs" and "All jobs"?

Or make a single page with site filters for "root" role and without for others.
