### ISSUE TITLE
Test suite depends on texlive-fonts-extra

### ISSUE THREAD

**Issue by link2xt** [melmothx/amusewiki#242]
`texlive-fonts-extra` is not a required dependency, but the test suite and `script/install_fonts.sh` depend on Iwona font and maybe some others, which are contained in this package.

**Comment by link2xt** [comment]
See also related PR #243

**Comment by melmothx** [comment]
ok, this needs to be addressed, as that package is huge. Having TeX Gyre and CMU should be enough to run the tests.

**Comment by link2xt** [comment]
`t/site-options.t` still uses `Iwona` font. Since it is removed, the test has started failing.

```
vagrant@debian-9:/vagrant$ perl -Mblib t/site-options.t
1..34
# RSS entries: 3
ok 1 - RSS listing at 2
ok 2
ok 3
not ok 4 - No errors found
#   Failed test 'No errors found'
#   at t/site-options.t line 90.
# Wrong sansfont Iwona!
...
```

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> t/site-options.t still uses Iwona font. Since it is removed, the test has started failing.
>
> vagrant@debian-9:/vagrant$ perl -Mblib t/site-options.t
> 1..34
> # RSS entries: 3
> ok 1 - RSS listing at 2
> ok 2
> ok 3
> not ok 4 - No errors found
> #   Failed test 'No errors found'
> #   at t/site-options.t line 90.
> # Wrong sansfont Iwona!

This is fixed now but I suspect there is more breakage going on (not
related to fonts, though).

-- 
Marco

**Comment by melmothx** [comment]
I believe this is fixed.
