### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by link2xt** [melmothx/amusewiki#254]
This should help with #164. It is easier than providing packages for all distributions.

I have not used Docker myself, but going to try it after finishing Carton support (#253).

Then we can simplify installation instructions and leave three options:
 1. Manual installation: as portable as possible, suitable for all *nix-based operating systems.
 2. Docker: Linux only
 3. Debian packages: Debian and Debian-based distributions

IMO it is better than current state where we have outdated (referencing TeX Live 2015 and 2017) FreeBSD- and CentOS-specific installation instructions.

**Comment by melmothx** [comment]
@link2xt  Yes, that's for sure a very nice initiative even if I'm not a fan of such container and I'm glad you're taking action on this.

**Comment by link2xt** [comment]
https://github.com/metacpan/metacpan-api has an example of Dockerfile for Catalyst web application

**Comment by link2xt** [comment]
Example of building base image with dependencies installed by Carton:
https://docs.docker.com/samples/library/perl/#example-creating-a-reusable-carton-image-for-perl-projects

**Comment by yodatak** [comment]
Don't know if it could be useful but i made something for just using amusewiki tools https://github.com/yodatak/amusewikitooling-docker

**Comment by melmothx** [comment]
@yodatak that would the quick and straightforward approach, right, to build the image.

I think the problem is how to mount the repositories, databases, webserver configuration for persistence of important data.

**Comment by melmothx** [comment]
Working on this Docker thing.

**Comment by yodatak** [comment]
I change my https://github.com/yodatak/amusewikitooling-docker and try to use alpine but i got some fonts issue LaTeX Font Warning: Some font shapes were not available, defaults substituted.

`muse-compile.pl ok.muse`

**Comment by melmothx** [comment]
yodatak <notifications@github.com> writes:

> I change my https://github.com/yodatak/amusewikitooling-docker and try
> to use alpine but i got some fonts issue LaTeX Font Warning: Some font
> shapes were not available, defaults substituted.

Can you send the full log? It's possible that you're missing fonts. What
`fc-list | grep CMU` says? The CMU fonts are the default one. Can you
try with some other fonts, E.g.

`muse-compile.pl --pdf --extra mainfont="Linux Libertine O"`

or 

`muse-compile.pl --pdf --extra mainfont="TeX Gyre Pagella"`


-- 
Marco

**Comment by decentral1se** [comment]
https://github.com/rojenzaman/amusewiki-docker is a thing also? Trying it now...

**Comment by decentral1se** [comment]
Ran into a couple of issues, I'm unsure how to deal with them:

> https://github.com/rojenzaman/amusewiki-docker/issues/created_by/decentral1se

Basically, how to get amusewiki to play nicely with traefik as a proxy.... I don't need amusewiki to generate certificates for nginx, TLS is terminated at the traefik layer... so then I think I just need to set the site domain and generate the config but I'm unsure how to do that on the CLI?

**Comment by decentral1se** [comment]
Is it possible to config an intial site domain/url from the `amusewiki set-site-variable --all --set ...` interface?

I think that might be what I need i.e. https://github.com/rojenzaman/amusewiki-docker/issues/3#issuecomment-1242538479

**Comment by melmothx** [comment]
The initial config can be set when calling the configure script: 
https://github.com/rojenzaman/amusewiki-docker/blob/master/texlive-base/Dockerfile#L69

**Comment by decentral1se** [comment]
Yeh I would close this off and link to https://github.com/rojenzaman/amusewiki-docker, it works.

**Comment by decentral1se** [comment]
https://git.coopcloud.tech/coop-cloud/amusewiki
