### ISSUE TITLE
Use npm/yarn to install JavaScript and CSS code

### ISSUE THREAD

**Issue by link2xt** [melmothx/amusewiki#263]
Currently Bootstrap, Fork Awesome, CKEditor and highlight.js are installed manually or by downloading from CDNs (see `script/install_js.sh`). CKEditor is even downloaded over HTTP. All of them are available in npm.

There is some work required to make it work with Debian packaging, but after all it is possible to bundle all JS and CSS at the build stage, so npm is not required on the user machine.

**Comment by melmothx** [comment]
@link2xt I'm not sure, in this context, if the over-engineered tooling is worth of. Bootstrap is kept in sync as submodule, together with Bootswatch. Fork Awesome at the moment is my fork (for the EPUB icon).

Highlight is loaded only on request, CKeditor only in selected pages, so they are not good candidates for bundling.

**Comment by melmothx** [comment]
Latest trend (see Ruby or Rails) is to go without all this tooling mess and at this point I'm happy it wasn't done.
