### ISSUE TITLE
Please add armhf architecture

### ISSUE THREAD

**Issue by traumschule** [melmothx/amusewiki#270]
Hi! Trying to install amusewiki on a RaspberryPI failed because armhf isn't supported by the pool. The packages install however, just getting their dependencies is tedious and i wondered if you could add that arch. Thanks for maintaining the debs, this is a great help for everyone!

```
# apt update                                
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Get:3 http://packages.amusewiki.org/debian stretch InRelease [2,523 B]
Reading package lists... Done
Building dependency tree
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://packages.amusewiki.org/debian stretch InRelease' doesn't support architecture 'armhf`
```

**Comment by melmothx** [comment]
@traumschule this should be done. Could you test it and let me know if it works for you?

**Comment by melmothx** [comment]
this should be completed, although there was no feedback.
