### ISSUE TITLE
Carton issues

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#278]
Starting with an empty `local` I get this:

! Couldn't find module or a distribution Catalyst::Devel (1.0)         
! Couldn't find module or a distribution DBIx::Class::Cursor::Cached

@link2xt can you reproduce it?

**Comment by link2xt** [comment]
I have cleaned the repository with `git clean -xffd` and then doing `vagran up` successfully installs all the required libraries from CPAN.

**Comment by melmothx** [comment]
hm, vagrant box has indeed no problem. Probably relates to modules installed system-wide. Hm.
