### ISSUE TITLE
Remove Daemon::Control based scripts

### ISSUE THREAD

**Issue by link2xt** [melmothx/amusewiki#280]
This issue is to continue discussion started in #265 PR.

Currently Amusewiki requires running four services:

 - Amusewiki web application: PSGI application, `psgi/amusewiki.psgi`
 - Jobber: job queue, `script/amusewiki-jobber`
 - cgit, serving the `/git` URL on `localhost:9015`, usually accessed via cgit proxy from `lib/AmuseWikiFarm/Archive/CgitProxy.pm`, which authenticates users. It is managed by `psgi/amusewiki-cgit.psgi` or nginx+fcgiwrap.
 - nginx web server, mostly handling static files, rewriting old URLs, managing HTTPS and running cgit on manual setups (see #245)

For systems with systemd, there is a `script/generate-systemd-unit-files`, which generates units for the first three services. That is what `Vagrantfile` uses now, except that `cgit` is managed by nginx and fcgiwrapper instead of its own service. For other initialization systems, such as [BSD init](https://man.openbsd.org/rc.d.8), similar services are easy to create as all of them require running a single daemon (it is better to document it once #245 is resolved and there is one preferred way to run cgit).

There is an alternative setup, based on `Daemon::Control`-based Perl scripts:
 - `script/init-fcgi.pl`, which manages Amusewiki web application
 - `script/jobber.pl`, which manages Jobber
In this setup, these two services are started manually or with `init-all.sh` and nginx manages cgit.

I propose removing `Daemon::Control` scripts, as neither development nor production setups are using it. They also require installing `Daemon::Control` system-wide, which does not make much sense now that all packages are installed via Carton.

**Comment by melmothx** [comment]
I' d like to have this straighten up as well, *but* there is an important case missing: installations without services, started from an `@reboot` cronjob calling `init.sh`. In this case the `Daemon::Control` scripts are needed, I think. I may be argued that you need root anyway to install the nginx configuration, and that's true. But if you don't add sites, the nginx part is quite stable, so the upgrades, etc. can be managed by the unprivileged user. Having the services installed means mandatory root access for each upgrade.

**Comment by link2xt** [comment]
With systemd, users can run these services with `loginctl enable-linger` using similar unit files.

**Comment by link2xt** [comment]
> But if you don't add sites, the nginx part is quite stable, so the upgrades, etc. can be managed by the unprivileged user. Having the services installed means mandatory root access for each upgrade.

Systemd unit files are also stable, there is no need to manage them on upgrades.

Well, maybe `Daemon::Control` can be kept there, for example for BSD user setups without systemd, but at least they can start the same daemons.

Can `script/amusewikifarm_fastcgi.pl` be removed and `init-fcgi.pl` changed to run `psgi/amusewiki.psig`?

**Comment by melmothx** [comment]
Yeah, the autogenerated scripts (with the notable exception of _create.pl, which was a bad idea to start with, but now it's there and there is no point in removing it) can go, superseded by plackup (as you migrate init-fcgi.pl, as suggested).

**Comment by melmothx** [comment]
@link2xt Ok, after some mumbling, I think it's not a good idea to remove the Daemon::Control scripts, enforcing a particular setup which in some cases is not desirable.

Regarding cgit: in Vagrant you can use the service as well, if you remove the wrapper root/git/cgit.cgi after the script/install.sh execution (same as it's done in the CentOS install notes). I'm very reclutant to remove a setup which has been here since the beginning, it's proved to work, and in some case would make the situation worse, not better (like cgit running as same user as the application).

Right now the Daemon::Control scripts are just wrappers for what the services do. I think this issue can be closed?
