### ISSUE TITLE
Skip translation tags

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#291]
This doesn't make sense to me as only a few tags will be translated and the author probably doesn't have a chance to add his own translations of the tags.

In addition it is really confusing if you enter "Email" as tag and see "E-Mail" as outcome - and don't know why this is happening.

**Comment by melmothx** [comment]
I think the translation should be restricted to multilanguage sites defining their own local translation, when they leverage the topic code. Agreed that this should be corrected, thanks for the report, doesn't make sense to use the pool of system-wide translations for the topics.

**Comment by racke** [comment]
How could I define local translations?

**Comment by melmothx** [comment]
https://amusewiki.org/library/localization#toc3
