### ISSUE TITLE
Inconsistent epub downloads

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#294]
There seems to be problem with epub downloads, they are flagged as "Soft 404" in the Google search console and curl has also complaints.

< HTTP/1.1 200 OK
< Server: nginx/1.6.2
< Date: Wed, 17 Apr 2019 10:06:20 GMT
< Content-Type: application/epub+zip
< Content-Length: 31089
< Last-Modified: Tue, 02 Apr 2019 09:20:14 GMT
< Connection: keep-alive
< Cache-Control: no-cache
< ETag: "5ca3294e-7971"
< Accept-Ranges: bytes
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 16108)
* Closing connection 0

**Comment by racke** [comment]
Looks like epub isn't a recognized file type for Google: https://support.google.com/webmasters/answer/35287?hl=en.

So we might exclude it from the index.

**Comment by melmothx** [comment]
Yeah, thanks for the debugging!

**Comment by melmothx** [comment]
Well, I'm puzzled. The header for the generated files already have the header noindex as per https://support.google.com/webmasters/answer/93710?hl=en


```
curl -I https://amusewiki.org/library/manual.epub
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Mon, 22 Apr 2019 07:18:27 GMT
Content-Type: application/epub+zip
Content-Length: 87076
Connection: keep-alive
Cache-Control: no-cache
Last-Modified: Sun, 21 Oct 2018 14:27:49 GMT
X-Catalyst: 5.90114
X-Robots-Tag: noindex
ETag: W/"da39a3ee5e6b4b0d3255bfef95601890afd80709"
```

I'm going to add a `rel="nofollow"` in the download links, which should do.

**Comment by melmothx** [comment]
It seems that the issue is fixed.
