### ISSUE TITLE
Buster release

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#299]
The following problems have been found:

 1. dbconfig common + DBD::Pg are failing epically to play together. dbconfig doesn't specify a port, while the driver is using the port of PG 9 (5432) instead of the current 5433.

 2. the amusewiki-extra-fonts is not considered good because of fonts file renaming. This should be fixed by a new release for buster only.

**Comment by melmothx** [comment]
These two items have been addressed.

**Comment by racke** [comment]
If I may ask, how did you address these problems?

**Comment by melmothx** [comment]
It's here:

https://github.com/melmothx/amusewiki/commit/f5e3f656d9c5848db3fdbe7257c11807cf1857a3

AFAIK, pg uses those two ports for parallel installation. So I check which one is open. It doesn't look bulletproof, though, but at the time I tested it (with dpkg crashing on me) it worked.

**Comment by racke** [comment]
Yes if you have multiple versions installed:

root@belukha:~# pg_lsclusters
Ver Cluster Port Status Owner    Data directory               Log file
9.6 main    5432 online postgres /var/lib/postgresql/9.6/main /var/log/postgresql/postgresql-9.6-main.log
10  main    5433 online postgres /var/lib/postgresql/10/main  /var/log/postgresql/postgresql-10-main.log
11  main    5434 online postgres /var/lib/postgresql/11/main  /var/log/postgresql/postgresql-11-main.log

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> Yes if you have multiple versions installed:
>
> root@belukha:~# pg_lsclusters
> Ver Cluster Port Status Owner    Data directory               Log file
> 9.6 main    5432 online postgres /var/lib/postgresql/9.6/main /var/log/postgresql/postgresql-9.6-main.log
> 10  main    5433 online postgres /var/lib/postgresql/10/main  /var/log/postgresql/postgresql-10-main.log
> 11  main    5434 online postgres /var/lib/postgresql/11/main  /var/log/postgresql/postgresql-11-main.log

I think the original problem was that I installed buster and after the
installation I nuked old postgresql. So what happened here is that there
was pg on 5433 and nobody listening on 5432. That patch addresses that
problem (and here I think it's better to add 5434 as well...).

Remains unclear how in the scenario you're showing here dbconfig would
behave. It it returns the dbport, we're good. If not, well, we're back
to square zero and not much we can do.

--
Marco

**Comment by racke** [comment]
I think you would need a more clever logic than iterating the ports.

**Comment by racke** [comment]
And dbconf can't know when you mess around with Pg major versions.

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> I think you would need a more clever logic than iterating the ports.

Well, I'm open to suggestions. The problem is that it seems that
dbconfig is not returning a port for a user/db which itself creates.
The include file I have looks like this:

/var/lib/amusewiki# cat dbinfo.conf
##
## database access settings in /bin/sh format
## automatically generated from /etc/dbconfig-common/amusewiki.conf
## by /usr/sbin/dbconfig-generate-include
##
## by default this file is managed via ucf, so you shouldn't have to
## worry about manual changes being silently discarded.  *however*,
## you'll probably also want to edit the configuration file mentioned
## above too.
##

dbuser='amusewiki'
dbpass='xxxxxxxxxx'
basepath=''
dbname='amusewiki'
dbserver='localhost'
dbport=''
dbtype='pgsql'

And in /etc/dbconfig-common/amusewiki.conf

# dbc_dbport: remote database port
#       leave unset to use the default.  only applicable if you are
#       using a remote database.
dbc_dbport=''

So, see, for local databases it seems that it's going to be always
empty.

Now, what would be the default, that's the question. The DBD::Pg driver
used 5432 unconditionally unless in the DNS you specify the port (which
is what I did here), while dbconfig was picking 5433.

Please note that this dbconfig-common stuff is used only at install
time. Once the dbic.yaml file is in place, that's what is used.

So this patch addresses the case where Pg is running, but not on 5432.
I'm wondering what would happen in a scenario like yours.

An idea could be to iterate over the ports and check if the user/pass/db
actually gives back a db handle or not.

The impression here is that this is working around a dbconfig-common
bug, though.

--
Marco

**Comment by melmothx** [comment]
I believe that the fix is sufficient. pg_upgradecluster is doing the right thing. This mess was created by a sloppy upgrade (removing the 9.5 dbs, not upgrading them).
