### ISSUE TITLE
Arbitrary attachments

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#300]
Like audio/video or other files.

**Comment by seth1** [comment]
I'm the original requester over in irc.
In addition to arbitrary attachments (which to me seems to be the best way of handling non-text content), would also be to add a special flair, eg:

`#title encyclopedia britannica edition 12
#author encyclopedia Britannica inc
#attach a.pdf b.pdf etc.pdf
#type nontext
OCR`
The non-text flag is nothing more than to indicate it's not really a text since it has not been adequately converted to amuse markup. This would give it a third icon (rather than the article and book icons), disable page calculation, and disable generating derivative formats. Once it is adequately converted the user could simply remove the flair to be treated as a normal 'correct' item type.

**Comment by melmothx** [comment]
@seth1 I agree with the desired behavior here. Probably that `type` flag is a bit too generic, I'm thinking about a boolean flag instead, like `#external 1` or `#binary 1`

The thing should be implemented in two steps.

First step: allow arbitrary files via git, in the repo's `upload` directory, with indexing, serving, handling of the flag and display on the text page. This should give everything what is needed to power users using the git workflow.

Second step: allow upload from the UI. This is a bit more complicated because 1. normally the webserver blocks requests too large, so that needs to be handled, and the setting should be allowed from the advanced site configuration (with that warning that you should have enough memory). A bit of research is needed if Catalyst can stream the upload directly to the disk instead of holding it into memory. Still mumbling if this is needed or reasonable. Probably you don't want to upload stuff like 1Gb file via web anyway. This step includes the mime type checking and setting, the serving from the staging area, the display of an icon like the PDF in the UI, the listing in the confirm page.

As you can see, the undertaking is not trivial, but it's totally worth the trouble.

**Comment by seth1** [comment]
As for step 2 amusewiki itself blocks files that are larger than 8 megabytes by the variable maxFileSize here:
https://github.com/melmothx/amusewiki/blob/master/root/static/js/amw-batch-upload.js#L190
If the user changes this line then all is well.

As for type to a boolean that sounds good

**Comment by melmothx** [comment]
@seth1 well, it also depends on the `client_max_body_size` in nginx, so the two variables need to be kept in sync

**Comment by melmothx** [comment]
@seth1 Ok, so I think the first stage is complete, save for eventual bugs lurking somewhere.

You're welcome to take a look at the staging site.

https://staging.amusewiki.org/library/test

Please note that the browser doesn't support all the mime types, but I think it's fine anyway.

I'm not sure I like the idea of having the administrator to decide which mime type to serve and which not. For now I compiled a list of files which makes sense to serve:

https://github.com/melmothx/amusewiki/blob/binary-uploads-300/lib/AmuseWikiFarm/Utils/Paths.pm#L122

For now I think it's good enough, without further configuration. If you send me your email, I can give you an account on the staging site to take a look as a logged in user.

Second stage is due when I get some time next week. If you are comfortable with the git workflow for uploading, and you want it released before the stage two, just let me know and I think it's reasonable safe to release. Otherwise to be continued next week.

**Comment by melmothx** [comment]
@seth1 The second stage is done as well. 

If you want to help and give it a try, this is the right moment. These attachments are allowed to logged in only, so please contact me via mail and I'll give you an account for the staging site.

If I don't hear from you I'm releasing it over the weekend or at the beginning of the next week.
