### ISSUE TITLE
Skip confirmation page for logged in if there's nothing.

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#303]

**Comment by melmothx** [comment]
Implementation  details:

The less invasive solution seems to be a JS thing which on the pending change will click the publish button if only one is present, while on publish thing  will redirect back to the page when the publishing process is over.

**Comment by racke** [comment]
Well it should also work if there are multiple pending changes.

**Comment by melmothx** [comment]
The change seems fairly straightforward:

- [ ] Add express_publishing (boolean) to the site table (so it's straight-forward to upgrade whole installations via DB console instead of jumping between panels to upgrade them all.
- [ ] The controller code which publish the revision is tiny, its logic can be added to https://github.com/melmothx/amusewiki/blob/910c8ee9624f0c99af4560a32e428ca0d244e0c1/lib/AmuseWikiFarm/Controller/Edit.pm#L590  from  https://github.com/melmothx/amusewiki/blob/910c8ee9624f0c99af4560a32e428ca0d244e0c1/lib/AmuseWikiFarm/Controller/Publish.pm#L145
- [ ] In the jobber log page, add js code which will redirect to the target page once the job has finished.

**Comment by melmothx** [comment]
This looks done. Demo available at https://staging.amusewiki.org

**Comment by racke** [comment]
Yeah that's better, thanks!

**Comment by melmothx** [comment]
I think this is not working as expected, as I'm experiencing a stop on revision selection when it shouldn't. Maybe old revisions are in the way?

**Comment by melmothx** [comment]
I think this is sorted out.
