### ISSUE TITLE
(feature) designate templates on a per-text basis

### ISSUE THREAD

**Issue by mouseb** [melmothx/amusewiki#310]
perhaps this is already possible.

i would like to be able to add texts to a library that have recommended or imposed template options just for them associated with them. so instead of just saying x y and z templates are available for the whole archive, a single text might have its own template. the idea being that the a particular book for example needs to be formatted a5 landscape, another one trimmed a4, etc.

edit:
i see that bookbuilder has an savable options template built-in. but i'm unsure if the uploader can forward specs to the users bookbuilder? 
but in any case, it wd be ideal if these kinds of template settings were valid for all output options for a single book.

i didn't manage to find much documentation about either kind of templates.

**Comment by melmothx** [comment]
mouseb <notifications@github.com> writes:

> perhaps this is already possible.
>
> i would like to be able to add texts to a library that have
> recommended or imposed template options just for them. so instead of
> just saying x y and z templates are available for the whole archive, a
> single text might have its own template. the idea being that the a
> particular book for example needs to be formatted a5 landscape,
> another one trimmed a4, etc.

It's already possible (althought not documented, as experimental) to
have a different template per format. I have to mumble about this, even
if this feels like the next natural step.

--
Marco

**Comment by melmothx** [comment]
This needs documentation post-release

**Comment by melmothx** [comment]
@mouseb when you get the chance, please check 

https://staging.amusewiki.org/library/test-custom-formats-all-en (all formats)

and compare to

https://staging.amusewiki.org/library/test-de (only one format)

So once this change is released, you could designate the format by code in the header, like

`#formats c1 c2`

You can find the code in the formats overview /settings/formats

**Comment by mouseb** [comment]
@melmothx 
hi, i see how this is working, and it is working, but i'm still not 100% clear on the whole process coz i still don't know the software that well. 

so i have 2 questions, more about the design or process:

q1: can a librarian create a format when adding a text? or should they create a format, then add a text, then specify in the header as you say above?

q2: are these formats also sent to the bookbuilder? when i check your above test which has just the single format available, if i send it to the book builder i don't have the option to eg use that single format. instead i have to choose fonts etc. i was hoping a librarian could specify an eg imposed template for the bookbuilder as well, so that if you send a text to the bookbuilder and a librarian has specified that that text should be a5 landscape in xyz font, that information would be the bookbuilder defaults. 

but i'm not clear if bookbuilder templates ('option templates') are separate to the other normal ones (ie 'formats')...

maybe its also needs some docs on formats and templates, and how theyre separate if they are, because they are also v similar.

**Comment by melmothx** [comment]
mouseb <notifications@github.com> writes:

> @melmothx hi, i see how this is working, and it is working, but i'm
> still not 100% clear on the whole process coz i still don't know the
> software that well.

Yeah, I'm going to document it properly once the code is released.

> so i have 2 questions, more about the design or process:
>
> q1: can a librarian create a format when adding a text? or should they
> create a format, then add a text, then specify in the header as you
> say above?

No, the idea is the first you create the format, then specify it in the
header if you want just one (or more) specific format. Otherwise all
will be picked up, as it normally does.

> q2: are these formats also sent to the bookbuilder? when i check your
> above test which has just the single format available, if i send it to
> the book builder i don't have the option to eg use that single format.
> instead i have to choose fonts etc. i was hoping a librarian could
> specify an eg imposed template for the bookbuilder as well, so that if
> you send a text to the bookbuilder and a librarian has specified that
> that text should be a5 landscape in xyz font, that information would
> be the bookbuilder defaults.

Ok, forwarding that should not be a problem, but it's a different
problem (and makes sense as well).

> but i'm not clear if bookbuilder templates ('option templates') are
> separate to the other normal ones (ie 'formats')...

The set of options is the same, the guts of the code is shared, hence
they can be forwarded, just needs to be done.

> maybe its also needs some docs on formats and templates, and how
> theyre separate if they are, because they are also v similar.

Yes indeed.

--
Marco

**Comment by melmothx** [comment]
@mouseb documentation at https://amusewiki.org/library/templates-and-formats
