### ISSUE TITLE
categories, topics (docs unclear)

### ISSUE THREAD

**Issue by mouseb** [melmothx/amusewiki#311]
it's not very clear to me how topics and categories work and are different to each other and i find that the docs don't rly explain how they work.

i can go to manage categories and see that eg author is a type of category, and so is topic. then i see i can eg set up a topic list for navs basically like wiki tags. 

so topics seem straightforward but the nature of categories eludes me still! i cannot create them or rly organise them. they are auto created, but from what exactly? i take it the page headers?

usage: i would be interested in being able to filter my archive by original publisher. i see that muse supports #publisher as a header directive, but it doesn't seem to effect cats or topics. wd it be better to skip that header and just enter publisher names as topics?

**Comment by mouseb** [comment]
it wd also be great if adding #publisher to an entry would make that appear along w title, author, pub date, etc.

**Comment by melmothx** [comment]
I think here the category mechanism should be extended to allow arbitrary category types, beside topics and authors, so you could have publisher and whatever else that cannot be anticipated.

**Comment by melmothx** [comment]
@mouseb Please take a look here when you have the chance https://staging.amusewiki.org/category/publisher/my-publisher

This is still missing an admin console to add such categories, but logic should be in place.

**Comment by rojenzaman** [comment]
#400
