### ISSUE TITLE
installer feedback

### ISSUE THREAD

**Issue by mouseb** [melmothx/amusewiki#312]
just a little bit of feedback about the installer process, mayb not super important but thought id just mention it:

on installing from debian repos, i had the problem mentioned in the initial email. i cdn't access amusewiki from the suggested URL. the email mentions adding amusewiki.localdomain to your hosts file:
`If your browser can't find the server or shows you a default nginx
page, please edit your /etc/hosts file adding "amusewiki.localdomain" to the
127.0.0.1 line (or whatever IP you're trying to reach).`

i did that and it still didn't work. what i had to do was first run `hostname -i` to work out which IP address to specify (as there was more than one in the hosts file), then in /etc/hosts i had to make sure i added amusewiki.localdomain _before_ the existing entry for that IP. as in 
`1.2.3.4.     amusewiki.localdomain existinghostentry.`

if you put it _after_ existinghostentry it doesn't work.

(the output of `hostname -d` for me was initially blank, ie i had no domain specified)

**Comment by melmothx** [comment]
@mouseb I don't see how

```
127.0.0.1 first.domain second.domain
```

and 

```
127.0.0.1 second.domain first.domain
```

would make any difference. Here the instructions are a bit vague, because this could be a local install on 127.0.0.1, or a remote install, then the /etc/hosts file to edit is the browser's one. Improved docs on a41864bb

**Comment by mouseb** [comment]
@melmothx it does make a difference if one of those entries is only a host without a domain. the one with the .domain must precede the one that doesn't specify a domain:
`127.0.0.1    host.localdomain  host`
i just found this out on stackoverflow somewhere.
i installed via ssh.
it might only be an issue if your hosts are already edited, i'm not sure (mine had been changed by another web app).

**Comment by melmothx** [comment]
@mouseb`man hosts(5)` doesn't seem to hint about that, but I guess that is beyond this ticket's scope.
