### ISSUE TITLE
use attached files as cover image in the bookbuilder

### ISSUE THREAD

**Issue by mouseb** [melmothx/amusewiki#314]
if files are attached to an entry, can they not also be forwarded to the bookbuilder as possible cover images? that way the uploader or publisher of an entry can specify the cover image, rather than the user having to provide it at their end.

**Comment by melmothx** [comment]
mouseb <notifications@github.com> writes:

> if files are attached to an entry, can they not also be forwarded to
> the bookbuilder as possible cover images? that way the uploader or
> publisher of an entry can specify the cover image, rather than the
> user having to provide it at their end.

Not sure if this is a bug or a missing feature. I think it makes sense
in any case.

--
Marco

**Comment by melmothx** [comment]
@mouseb if you have the chance, could you test this feature on https://staging.amusewiki.org? Feel free to add a text with images and check with the bookbuilder. I'm still missing some cosmetics here but the logic should be good.
