### ISSUE TITLE
configure server email notifications (docs)

### ISSUE THREAD

**Issue by ghost** [melmothx/amusewiki#317]
it's unclear to me how to set up server notification emails (for eg confirming new librarians) and i can't find any dox about this.

i have filled out the "notify mail" and "site mail" fields in the general conf, but that's not enough to set them up is it? does it need to be set up elsewhere on my server?

**Comment by melmothx** [comment]
mouseb <notifications@github.com> writes:

> it's unclear to me how to set up server notification emails (for eg
> confirming new librarians) and i can't find any dox about this.
>
> i have filled out the "notify mail" and "site mail" fields in the
> general conf, but that's not enough to set them up is it? does it need
> to be set up elsewhere on my server?

That should be it.

Doesn't work for you? Which email doesn't trigger? Does the logs in
/var/lib/amusewiki/log/*.log say something?

--
Marco

**Comment by mouseb** [comment]
@melmothx  i don't receive any emails. but i just entered a personal email address, i have no mail server on my box. surely an external email address wd require providing credentials? (thats how it works at least on my nextcloud server.)

the log just reports successful sending of the emails

**Comment by melmothx** [comment]
mouseb <notifications@github.com> writes:

> @melmothx i don't receive any emails. but i just entered a personal
> email address, i have no mail server on my box. surely an external
> email address wd require providing credentials? (thats how it works at
> least on my nextcloud server.)

Not sure how that server is configured, but if correctly configured you
should be able to send mail from your machine without providing any
credential.

If you need SMTP, then you could try the instructions here:

https://amusewiki.org/library/install#toc12

together with

https://metacpan.org/pod/Email::Sender::Transport::SMTP (for the correct
variables to set, which would include sasl_username and sasl_password).

I'd suggest you to inspect the server logs.

--
Marco

**Comment by decentral1se** [comment]
Also see https://github.com/melmothx/amusewiki/issues/353.

**Comment by decentral1se** [comment]
It would be nice to have a `amusewiki testmail foo@example.com` command to test email sending?

**Comment by melmothx** [comment]
Mailing depends on environment variables. So a test would need to send a mail both from the site and from a background job.
