### ISSUE TITLE
pdf preview

### ISSUE THREAD

**Issue by ghost** [melmothx/amusewiki#318]
mayb this is useless wishlish item...

but for my use case at least itd be super handy to be able to generate a pdf directly from the editing page. (similar set up to eg gummi latex editor or similar.)
main reason being that the html/browser spacing is totally different to the tex generated pdfs, and the latter is more important than the former for me.

**Comment by melmothx** [comment]
mouseb <notifications@github.com> writes:

> but for my use case at least itd be super handy to be able to generate
> a pdf directly from the editing page. (similar set up to eg gummi
> latex editor or similar.)

Of course it would, but in an environment of self-hosting and/or small
fishes, you can't afford to have latex running at full speed, with
concurrency risking to cripple the server. That's way the compilation is
delegated to a background daemon and not done directly by the web
application.

Probably using the very same font on the web is going to help. Maybe try
to add a rule to the local.css file for the repo to intercept the
preview body?

--
Marco

**Comment by mouseb** [comment]
ah ok, thx for explaining.

yeah i didn't get around to working on modifying the web stuff at all yet, but will try out yr suggestion.

**Comment by melmothx** [comment]
Original poster gone. Question answered, closing.
