### ISSUE TITLE
word import: import verse?!

### ISSUE THREAD

**Issue by mouseb** [melmothx/amusewiki#319]
another blatant wishlist item: if i'm importing documents with lines all over the page (ie manually spaced in from the left hand margin), is it possible for the converter to recognise them by prefixing them with the > muse tag?

**Comment by melmothx** [comment]
mouseb <notifications@github.com> writes:

> another blatant wishlist item: if i'm importing documents with lines
> all over the page (ie manually spaced in from the left hand margin),
> is it possible for the converter to recognise them by prefixing them
> with the > muse tag?

Short version: no.

It depends a lot on which is the producer software, which kind of HTML
emits. So you're going to have different HTML on LibreOffice (depends on
version as well), on Word, etc.

Also the verse environment is semantical and difficult (if possible at
all) to distinguish from a quotation (and even these I'm not sure how
they are picked up nowadays).

Needless to say, spacing in the HTML is very fragile as well....

--
Marco

**Comment by mouseb** [comment]
hehe sure thing, thought it was a long shot.

**Comment by melmothx** [comment]
Closing this, I don't see happening in the foreseeble future.
