### ISSUE TITLE
Descriptions for topics and authors can't be deleted

### ISSUE THREAD

**Issue by tinglado** [melmothx/amusewiki#32]
As is stated in https://amusewiki.org/library/maintainer-s-faq#toc7 an user can add a description. This works well but how I can delete the description? I tried to do it leaving the form blank but in that case the text is not updated. If I only put a space the text doesn't appear (well, only the space) but the rectangle still is there so it's not a solution. I need to remove the description because I just only want to test the feature but not use it yet.

**Comment by melmothx** [comment]
tinglado <notifications@github.com> writes:

> As is stated in https://amusewiki.org/library/maintainer-s-faq#toc7 an
> user can add a description. This works well but how I can delete the
> description? I tried to do it leaving the form blank but in that case
> the text is not updated. I need to remove the description because I
> just only want to test the feature but not use it yet.

This is a missing feature indeed and I'm fixing that. For a sloppy
workaround (until the next release) try to send just some empty lines or
a single <br>. The block will still appear, though.

-- 
Marco

**Comment by melmothx** [comment]
@tinglado Fixed, but I'm waiting for some feedback on the the bookbuilder partial (see private mail) before releasing it.

**Comment by tinglado** [comment]
Good, thank you.

I'm aware of the changes in the bookbuilder so I've done a test but I have nothing to say for now. I will check it today with more time.
