### ISSUE TITLE
Add current changes to edit page

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#329]
It would be very useful to show the current changes on the edit page (or at least a link to display them).

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> It would be very useful to show the current changes on the edit page
> (or at least a link to display them).

The link should be already there (the +- icon on the top-right corner of
the preview box. Does this help?

--
Marco

**Comment by racke** [comment]
That helps, but it is not super obvious. Can you add "Changes" left of the +- Icon?

**Comment by melmothx** [comment]
done, thanks for the suggestion!
