### ISSUE TITLE
Can't enter empty publication date when creating a new document

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#330]
![Zur Bibliothek hinzufügen   Wegatrade wiki](https://user-images.githubusercontent.com/143678/74422560-192d3f00-4e4f-11ea-81e2-02987eb38f6c.png)

Even if I select nothing, I got a publication date in my new document:

`#pubdate 2020-02-13T09:54:11`

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> ![Zur Bibliothek hinzufügen   Wegatrade wiki](https://user-images.githubusercontent.com/143678/74422560-192d3f00-4e4f-11ea-81e2-02987eb38f6c.png)
>
> Even if I select nothing, I got a publication date in my new doucment:
>
> `#pubdate 2020-02-13T09:54:11`

Because the default (left empty) is now. You can always remove the line
from the header to have it dynamically updated each time you update the
file.

Does this help?

--
Marco

**Comment by racke** [comment]
Well it is a kind of repetitious as I usually don't want to set a publication date. On top of that the message below the input box carries a false promise.

**Comment by melmothx** [comment]
Then I guess a new configuration option is needed.
