### ISSUE TITLE
Simplify the git remote setup

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#336]
It was pointed out that the setup  is "immensely complicated" (well, I've seen worse honestly). However, reviewing the documentation it's seems clear that it's not straightforward either.

So the idea would be to get amusewiki to create automatically a shared (by group) repository where local users can push. So the instructions would boil down to: have a local user? add it to the amusewiki group and push here. Do not have a local user? Go to github/gitlab, setup one, and paste here the URL, so we can push.

**Comment by racke** [comment]
So let's look at it from my point of view as considerable lazy user who doesn't care about AmuseWiki's innards. I would expect the following workflow:

1. clone from the Git url provided by AmuseWiki
2. push my changes (without fiddling with branches)
3. documentation is refreshed
4. optionally receive notification about completion
