### ISSUE TITLE
Feature request: Batch editing for SORTtopics metadata

### ISSUE THREAD

**Issue by ienzo** [melmothx/amusewiki#341]
I'd like a way to batch edit topics, rename topics from topic pages, and a way to merge practically identical topics without going in and manually changing the SORTtopics of each article.

I would like to consolidate topics that are virtually identical except in wording on The Anarchist Library. 

For example I'd like a way to merge the topics `Kropotkin`, `Peter Kropotkin`, and `Pëtr Kropotkin` to just `Pëtr Kropotkin`. Perhaps tags with `Kropotkin` or `Peter Kropotkin`, could be forwarded to `Pëtr Kropotkin`? Or perhaps it would be metadata batch-editor? 

Currently the only way to merge topics is to go into each erring article and manually changing the SORTtopics. This is really labor intensive. Perhaps a new tool could streamline it?

**Comment by melmothx** [comment]
ienzo <notifications@github.com> writes:

> Currently the only way to merge topics is to go into each erring
> article and manually changing the SORTtopics. This is really labor
> intensive. Perhaps a new tool could streamline it?

No, that's not correct. There is /console/alias (Redirections under the
user menu) which can be used for this purpose, aliasing the
author/topics and redirecting accordingly. It's maybe not super-handy
but that was done in the past and worked, without going via the local
editing path.

-- 
Marco

**Comment by melmothx** [comment]
Closing this, assuming question was answered.
