### ISSUE TITLE
Automatic toc labels instead of numbers

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#342]

**Comment by melmothx** [comment]
This is under testing on https://staging.amusewiki.org

**Comment by racke** [comment]
Seems to work: https://staging.amusewiki.org/library/test-123#amw-toc-defined.
It is a bit inconsistent which existing labels such as https://staging.amusewiki.org/library/test-123#text-amuse-label-filtertrim, but definitely an improvement.

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> Seems to work: https://staging.amusewiki.org/library/test-123#amw-toc-defined.

> It is a bit inconsistent which existing labels such as
> https://staging.amusewiki.org/library/test-123#text-amuse-label-filtertrim,
> but definitely an improvement.

I guess it can be changed to a more consistent name like
#text-amuse-toc-XYZ, but I'm pretty sure it needs to be a different
prefix to avoid clashing.

In theory the document could be checked for existings IDs, but not sure
if worth the trouble, as conceptually they are two different things (an
arbitrary label and a toc entry on sugar).

-- 
Marco

**Comment by melmothx** [comment]
If the section has a label, use that instead of the stringified one.
