### ISSUE TITLE
Include files causing warning

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#349]
```
Job git started at Thu Aug 20 13:22:00 2020
commit e832acb30fc44d3ce66703822ed2e0a28fac2f80
URL: https://docpad.icdev.de/git/docpad/commit/?id=e832acb30fc44d3ce66703822ed2e0a28fac2f80
Author: Stefan Hornburg (Racke) <racke@linuxia.de>
Date:   Thu Aug 20 13:21:47 2020 +0200

    Fix import syntax.
Updating 531f41f..e832acb
Fast-forward
 t/tt/test.muse | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
From ./shared/repo/docpad
 * branch            master     -> FETCH_HEAD
WARNINGS intercepted:
Discarding include/foobar.muse, expected path is f/fr/foobar.muse
Job git finished at Thu Aug 20 13:22:00 2020
```
Contents of `test.muse`:
```

#title Test

Please advise.

#include include/foobar.muse

```

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> ```
> Job git started at Thu Aug 20 13:22:00 2020
> commit e832acb30fc44d3ce66703822ed2e0a28fac2f80
> URL: https://docpad.icdev.de/git/docpad/commit/?id=e832acb30fc44d3ce66703822ed2e0a28fac2f80
> Author: Stefan Hornburg (Racke) <racke@linuxia.de>
> Date:   Thu Aug 20 13:21:47 2020 +0200
>
>     Fix import syntax.
> Updating 531f41f..e832acb
> Fast-forward
>  t/tt/test.muse | 2 +-
>  1 file changed, 1 insertion(+), 1 deletion(-)
> From ./shared/repo/docpad
>  * branch            master     -> FETCH_HEAD
> WARNINGS intercepted:
> Discarding include/foobar.muse, expected path is f/fr/foobar.muse
> Job git finished at Thu Aug 20 13:22:00 2020
> ```
> Contents of `test.muse`:
> ```

Well, that is a false alarm, as there is no way to determine if that is
an included file or simply a misplaced file. The inclusion did happen.

I'd suggest to rename the included file as foobar.muse.inc or remove the
extension.

-- 
Marco

**Comment by racke** [comment]
Fair enough, but in that case the documentation should be adjusted.

**Comment by melmothx** [comment]
Closed by https://github.com/melmothx/amusewiki-site/commit/412cf1d2880f1a8523c55d70a784b675ed4098ce
