### ISSUE TITLE
Add default login button to top menu?

### ISSUE THREAD

**Issue by decentral1se** [melmothx/amusewiki#355]
Easier for other admins to click to get in when they don't know the /login/ URL. I know I can add this to the "More..." bar myself but I am wondering if this could also be a high-level button or if anyone else has an opinion on this.

**Comment by melmothx** [comment]
Honestly I've always been annoyed by login boxes on sites where the need of a login is not obvious and not needed by 99% of the users. As you noted, it's trivial to add to the menu if that is wanted.

**Comment by decentral1se** [comment]
Fair enough!
