### ISSUE TITLE
Additional perl pakages required for Debian Buster install + password/SSL SMTP mail configuration

### ISSUE THREAD

**Issue by decentral1se** [melmothx/amusewiki#358]
Related to https://github.com/melmothx/amusewiki/issues/353.

I end up with:

```
Environment="EMAIL_SENDER_TRANSPORT=SMTP"
Environment="EMAIL_SENDER_TRANSPORT_ssl=1"
Environment="EMAIL_SENDER_TRANSPORT_host=mail.somewhere.net"
Environment="EMAIL_SENDER_TRANSPORT_port=465"
Environment="EMAIL_SENDER_TRANSPORT_sasl_username=foo@bar.com"
Environment="EMAIL_SENDER_TRANSPORT_sasl_password=foobar"
```

And then I saw the following error:

> failed: SMTP auth requires MIME::Base64 and Authen::SASL at /usr/share/perl5/Email/Sender/Transport/SMTP.pm line 162.

So I was able to resolve with:

```
$ apt install libmime-base64-urlsafe-perl libauthen-sasl-perl
```

Maybe another one for the documentation!

**Comment by melmothx** [comment]
I think that the urlsafe module is not really needed, MIME::Base64 is a core one.

Added Authen::SASL to the dependencies, it makes little sense to put the burden on the user just to save the installation of a generic module.
