### ISSUE TITLE
Use 410 gone for deleted documents

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#360]
This helps search engines to delete pages from the index faster than using 404.

Quote from Wikipedia:

410 Gone
 
Indicates that the resource requested is no longer available and will not be available again. This should be used when a resource has been intentionally removed and the resource should be purged. Upon receiving a 410 status code, the client should not request the resource in the future. Clients such as search engines should remove the resource from their indices. Most use cases do not require clients and search engines to purge the resource, and a "404 Not Found" may be used instead.

**Comment by melmothx** [comment]
This is done and released in 2.509
