### ISSUE TITLE
Duplicate page appears in the search console

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#362]
The standalone HTML page is listed in the Google index. This shouldn't happen.
Suggestion: add tag to point to the canonical page.

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> The standalone HTML page is listed in the Google index. This shouldn't happen.
> Suggestion: add tag to point to the canonical page.

The weird thing is that those pages already have X-Robots-Tag: noindex
in the header. Any clue?

-- 
Marco

**Comment by racke** [comment]
I looked at the HTTP headers of the standalone HTML page and it misses X-Robots-Tag: noindex.

**Comment by melmothx** [comment]
This seems to relate to this problem (with possible solution)

https://stackoverflow.com/questions/24507157/adding-custom-http-headers-to-nginx-x-accel-redirect
