### ISSUE TITLE
Symlinks for images are not respected

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#370]
Example:

c-p-category-page-1.png -> category-entry.png

The picture shows in the Emacs' muse mode.

**Comment by racke** [comment]
Thanks a lot!

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) ***@***.***> writes:

> Thanks a lot!

Honestly the use-case is a bit weird, but it led to address a potential
symlink-based attack coming from untrusted external repos, so thanks for
the report.

-- 
Marco

**Comment by racke** [comment]
I would prefer to keep the name of the picture, but AMW forces me to use a non-descriptive one for no good reason (IMHO). My use case also allows to share pictures between for multiple docs.

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) ***@***.***> writes:

> I would prefer to keep the name of the picture, but AMW forces me to
> use a non-descriptive one for no good reason (IMHO).

It forces you to use a *prefix* for the image, so it can be as
descriptive as you want, as long as it has a prefix consistent with the
directory the text resides.

Say you have an image called "image.png" under t/tt/, and then an image
with the same image "image.png" under another directory. If you ask for
"/library/image.png", the app can't know which of the two images you're
asked for.

Call them t-t-image.png and x-x-image.png as explained
https://amusewiki.org/library/offline-editing-via-git#toc8 and you will
be good.

That's simply the layout of the tree and too much is built on those
assumptions at this point I'm afraid.

> My use case also allows to share pictures between for multiple docs.

Ok, that's a legit case and makes sense.

-- 
Marco

**Comment by racke** [comment]
I think it is logically to look up "image.png" in the current directory (where *.muse is living) first.

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) ***@***.***> writes:

> I think it is logically to look up "image.png" in the current
> directory (where *.muse is living) first.

The *URL* /library/image.png which serves the image is the problem, not
the lookup/compilation, as the tree is flattened. Ok, there's the
referrer, but that's not exactly a robust solution (at least, not for my
tastes), as URLs should be uniques.

A plain "wget $host/library/image.png" would not work.

-- 
Marco
