### ISSUE TITLE
latest upgrade: bash: line 0: kill: (7234) - No such process

### ISSUE THREAD

**Issue by decentral1se** [melmothx/amusewiki#373]
Tried to reboot to reset state but it seems to be something further than that, any ideas?

```
root@foo:~# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up amusewiki (2.516-1+amw1) ...
dbconfig-common: writing config to /etc/dbconfig-common/amusewiki.conf
Checking fontspec.json
Updated /var/lib/amusewiki/repo/amw lexicon
DDLs dir is /usr/share/perl5/AmuseWikiFarm/dbicdh
Checking if database is up-to-date: YES
amusewiki-nginx-reload.service is a disabled or a static unit, not starting it.
Backup amusewiki 7234 found, waiting 30 seconds then shutting it down
bash: line 0: kill: (7234) - No such process
dpkg: error processing package amusewiki (--configure):
 installed amusewiki package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 amusewiki
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by decentral1se** [comment]
Also, keyboard input is not respected during:

> Backup amusewiki 7234 found, waiting 30 seconds then shutting it down

So, you can't ctrl-c out of it :P

**Comment by decentral1se** [comment]
Hmmm, `rm /var/lib/amusewiki/amw.tmp.pid` fixed it :thinking:

**Comment by melmothx** [comment]
decentral1se ***@***.***> writes:

> Tried to reboot to reset state but it seems to be something further than that, any ideas?

I believe you have this file:

/var/lib/amusewiki/amw.tmp.pid

Which for some reason was left during a previous upgrade.

Kill all the various amusewiki process you may have around and rmove
that file, which obviously point to a non-existent pid.

Remove it and run apt again.


-- 
Marco
