### ISSUE TITLE
Tor hidden service support

### ISSUE THREAD

**Issue by stayinside** [melmothx/amusewiki#381]
As it currently stands amusewiki does not support tor hidden services. With the onion address added as a vhost in the admin settings, and in the nginx config all requests are redirected to the main domain.

**Comment by melmothx** [comment]
stayinside ***@***.***> writes:

> As it currently stands amusewiki does not support tor hidden services.
> With the onion address added as a vhost in the admin settings, and in
> the nginx config all requests are redirected to the main domain.

Did you check the "Do not redirect aliases to canonical" in the admin
settings?

-- 
Marco

**Comment by stayinside** [comment]
Yes this worked!
