### ISSUE TITLE
error on installing on OS X 10.15

### ISSUE THREAD

**Issue by Enrico68** [melmothx/amusewiki#384]
Hello , 

thanks for this great Wiki, but I am getting some problems installing on OS X. This is what I get from the installation script 

```
script git:(master) ✗ ./install.sh
-n Checking if perl is present:
YES
-n Checking if carton is present:
YES
-n Checking if fc-cache is present:
YES
-n Checking if update-mime-database is present:
YES
-n Checking if xapian-check is present:
YES
-n Checking if openssl is present:
YES
-n Checking if cpanm is present:
YES
-n Checking if make is present:
YES
-n Checking if wget is present:
YES
-n Checking if git is present:
YES
-n Checking if unzip is present:
YES
-n Checking if rsync is present:
YES
-n Checking if gs is present:
YES
Installing perl modules
Installing modules using /Users/enricopirani/amusewiki/cpanfile (deployment mode)
Complete! Modules were installed into /Users/enricopirani/amusewiki/local
-n Checking installation of TeX live:
OK
Installing needed JS
Checking and installing missing fonts
CMU Serif OK
Linux Libertine O OK
Linux Biolinum O OK
TeX Gyre Termes OK
TeX Gyre Pagella OK
TeX Gyre Schola OK
TeX Gyre Bonum OK
TeX Gyre Heros OK
TeX Gyre Adventor OK
TeX Gyre Cursor OK
Charis SIL OK
Antykwa Poltawskiego OK
Antykwa Torunska OK
Iwona OK
PT Serif OK
PT Sans OK
Noto Sans OK
Noto Serif OK
DejaVu Sans OK
DejaVu Sans Mono OK
Creating fontspec.json
Can't exec "script/amusewiki-populate-webfonts": No such file or directory at /usr/local/Cellar/carton/1.0.34_2/libexec/lib/perl5/Carton/CLI.pm line 400.
```

**Comment by Enrico68** [comment]
after restarting from a clean new directory, stop compilation at : 

````
install -m 0755 -d /Users/enricopirani/amusewiki/opt/usr/lib/cgit/filters
cp -r filters/* /Users/enricopirani/amusewiki/opt/usr/lib/cgit/filters
Executing strip --strip-unneeded /Users/enricopirani/amusewiki/root/git/cgit.cgi
error: /Library/Developer/CommandLineTools/usr/bin/strip: unrecognized option: --strip-unneeded
Usage: /Library/Developer/CommandLineTools/usr/bin/strip [-AnuSXx] [-] [-d filename] [-s filename] [-R filename] [-o output] file [...]
strip --strip-unneeded /Users/enricopirani/amusewiki/root/git/cgit.cgi failed 256 at script/install-cgit.pl line 160.
````

**Comment by melmothx** [comment]
I believe you can continue the installation process as documented, the stripping is just optimization and the install.sh script has finished its job. Please let me know how it goes. Thanks

**Comment by Enrico68** [comment]
Ok, I have skipped the error and continue with : 

`➜  amusewiki git:(master) ✗ ./script/configure.sh  oran.local`

````
-n Checking DB connection:
OK
[DBICDH] [info] installing version 68
DBIx::Class::DeploymentHandler::Dad::install(): Install not possible as versions table already exists in database at ./script/amusewiki-create-doc-site line 111
`````

I have used `SQLite`. 
> Copy dbic.yaml.<dbtype>.example to dbic.yaml and adjust the credentials, and chmod it to 0600. (For SQLite is good as it is).

**Comment by melmothx** [comment]
Enrico Pirani ***@***.***> writes:

> Ok, I have skipped the error and continue with : 
>
> `➜  amusewiki git:(master) ✗ ./script/configure.sh  oran.local`
>
> ````
> -n Checking DB connection:
> OK
> [DBICDH] [info] installing version 68
> DBIx::Class::DeploymentHandler::Dad::install(): Install not possible as versions table already exists in database at ./script/amusewiki-create-doc-site line 111
> `````
>
> I have used `SQLite`. 
>> Copy dbic.yaml.<dbtype>.example to dbic.yaml and adjust the credentials, and chmod it to 0600. (For SQLite is good as it is).

Questions:

 1. Can you show me the content of $INSTALLATION_DIR/dbic.yaml?

 2. does the file referenced in the dsn exist? If so, please remove it 
    and run the configure.sh script again.

Please let me know.

Thanks

-- 
Marco

**Comment by Enrico68** [comment]
>1. Can you show me the content of $INSTALLATION_DIR/dbic.yaml?

 2. does the file referenced in the dsn exist? If so, please remove it
    and run the configure.sh script again.

this the content of my ` dbic.yaml` file

>amuse:
 8   dsn: 'dbi:SQLite:sqlite.db'
 7   user: ''
 6   password: ''
 5   on_connect_do: 'PRAGMA foreign_keys = ON'
 4   AutoCommit: 1
 3   RaiseError: 1
 2   sqlite_unicode: 1
 1   quote_names: 1

Have I to delete the content of dsn?

**Comment by melmothx** [comment]
Enrico Pirani ***@***.***> writes:

>>1. Can you show me the content of $INSTALLATION_DIR/dbic.yaml?
>
>  2. does the file referenced in the dsn exist? If so, please remove it
>     and run the configure.sh script again.
>
> this the content of my ` dbic.yaml` file
>
>>amuse:
>  8   dsn: 'dbi:SQLite:sqlite.db'
>  7   user: ''
>  6   password: ''
>  5   on_connect_do: 'PRAGMA foreign_keys = ON'
>  4   AutoCommit: 1
>  3   RaiseError: 1
>  2   sqlite_unicode: 1
>  1   quote_names: 1
>
> Have I to delete the content of dsn?

No, if there's a sqlite.db file in the installation directory, as I
suspect, please delete it and run the configure.sh again.

-- 
Marco

**Comment by Enrico68** [comment]
delete sqlite.db  configure again with 

`````
./script/configure.sh oran.local
-n Checking DB connection:
OK
[DBICDH] [info] installing version 68
[DBICDH] [info] deploying version 68
[DBICDH] [debug] Running SQL from /Users/enricopirani/amusewiki/dbicdh/SQLite/deploy/68/001-auto-__VERSION.sql
[DBICDH] [debug] Running SQL from /Users/enricopirani/amusewiki/dbicdh/SQLite/deploy/68/001-auto.sql
[DBICDH] [debug] Adding database version 68
<code> is already verbatim! in "=<code><verbatim>Material</verbatim></code>="
<code> is already verbatim! in "=<code><verbatim>Material</verbatim></code>="
No language found, assuming english
No language found, assuming english
No language found, assuming english
No language found, assuming english
No language found, assuming english
No language found, assuming english
No language found, assuming english
No language found, assuming english
Summary of the initial setup:

Host: "oran.local"
Site ID: "amw"
Root username: "amusewiki"
Root password: "sgradevole musulmani pastiglie vediamoci prendesse"

You should be able to login at http://oran.local/login with the above
credentials. This is going to be a dummy site with the documentation.

You can create a new site at http://oran.local/admin/sites

If your browser can't find the server or shows you a default nginx
page, please edit the /etc/hosts file on the browser's machine,
setting the IP for "oran.local":

E.g.

# local install, i.e. browser machine is the same as the server
127.0.0.1 localhost oran.local

# remote install. On the machine you are using (the client, the
# browser's machine), point to the server's IP

1.2.3.4 oran.local

Bootstrapping the initial site with the documentation
#####################################################

each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Document.pm line 75.
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Provider.pm line 376.
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Provider.pm line 875.
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Provider.pm line 894.
# please execute as root:
diff -Nu /etc/nginx/amusewiki_include /var/folders/bf/x0jstkkj0dg51h421_m18d3m0000gn/T/nginx-amusewiki-G5qjLEyR/amusewiki_include
cat /var/folders/bf/x0jstkkj0dg51h421_m18d3m0000gn/T/nginx-amusewiki-G5qjLEyR/amusewiki_include > /etc/nginx/amusewiki_include
diff -Nu /etc/nginx/sites-enabled/amusewiki /var/folders/bf/x0jstkkj0dg51h421_m18d3m0000gn/T/nginx-amusewiki-G5qjLEyR/amusewiki
cat /var/folders/bf/x0jstkkj0dg51h421_m18d3m0000gn/T/nginx-amusewiki-G5qjLEyR/amusewiki > /etc/nginx/sites-enabled/amusewiki
nginx -t && service nginx reload
#####################################################

You may want to start up application with ./init-all.sh start
`````
`````
➜  amusewiki git:(master) ✗ ./init-all.sh start
Installing modules using /Users/enricopirani/amusewiki/cpanfile (deployment mode)
Complete! Modules were installed into /Users/enricopirani/amusewiki/local
Imager loaded correctly
DDLs dir is /Users/enricopirani/amusewiki/dbicdh
Checking if database is up-to-date: YES
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Document.pm line 75.
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Provider.pm line 376.
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Provider.pm line 875.
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Provider.pm line 894.
# please execute as root:
diff -Nu /etc/nginx/amusewiki_include /var/folders/bf/x0jstkkj0dg51h421_m18d3m0000gn/T/nginx-amusewiki-IIsBbh9n/amusewiki_include
cat /var/folders/bf/x0jstkkj0dg51h421_m18d3m0000gn/T/nginx-amusewiki-IIsBbh9n/amusewiki_include > /etc/nginx/amusewiki_include
diff -Nu /etc/nginx/sites-enabled/amusewiki /var/folders/bf/x0jstkkj0dg51h421_m18d3m0000gn/T/nginx-amusewiki-IIsBbh9n/amusewiki
cat /var/folders/bf/x0jstkkj0dg51h421_m18d3m0000gn/T/nginx-amusewiki-IIsBbh9n/amusewiki > /etc/nginx/sites-enabled/amusewiki
nginx -t && service nginx reload
Updated repo/amw lexicon
Checking fontspec.json
current_version_is_2.522.txt
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Document.pm line 75.
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Provider.pm line 376.
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Provider.pm line 875.
each on anonymous hash will always start from the beginning at /Users/enricopirani/amusewiki/local/lib/perl5/darwin-2level/Template/Provider.pm line 894.
amusewiki-webapp                                              [Started]
amusewiki-jobber                                              [Started]
``````

I cannot open  http://oran.local/login 

`oran.local ha rifiutato la connessione.`

**Comment by melmothx** [comment]
Enrico Pirani ***@***.***> writes:

> amusewiki-webapp                                              [Started]
> amusewiki-jobber                                              [Started]
> ``````
>
> I cannot open  http://oran.local/login 
>
> `oran.local ha rifiutato la connessione.`

It looks to me that either nginx is not running or not configured or
/etc/hosts is missing an entry for oran.local. Nginx running without
amusewiki would lead to 502 bad gateway.

Can you check that out?

-- 
Marco

**Comment by Enrico68** [comment]
now got a `404 Not Found`.  This is my `nginx.conf` file 

`````

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  oran.local;


        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location /Users/enricopirani/ {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}
    include servers/*;
}
`````
thanks for your patience :-)

**Comment by melmothx** [comment]
I'd need the directory layout of the nginx config.

You can call the config generator with: `carton exec script/amusewiki-generate-nginx-conf`

It's expecting the nginx config to reside in /etc/nginx, so it's asking to create `/etc/nginx/amusewiki_include`  and `/etc/nginx/sites-enabled/amusewiki`. Now, the problem is that your conf is doing:

`include servers/*;`

Assuming the config is /etc/nginx/nginx.conf, as I expect, try to add to it:

```
include /etc/nginx/sites-enabled/*;
```

right after `include servers/*;`, same stanza.

Please keep me posted. Thanks.

**Comment by Enrico68** [comment]
forgot to tell you that on OSX  nginx.conf is located on `/usr/local/etc/nginx/`. Have to do the same ?

**Comment by melmothx** [comment]
Enrico Pirani ***@***.***> writes:

> forgot to tell you that on OSX nginx.conf is located on /usr/local/etc/nginx/. Have to do the same ?

OK, I see. Try this:

```
# as root
# create an include sites-enabled directory for nginx and log dir
mkdir -p /usr/local/etc/nginx/sites-enabled
mkdir -p /var/log/nginx/
# and add an include directive in nginx.conf inside the http { } stanza, at the end.
# include /usr/local/etc/nginx/sites-enabled/*;
vi /usr/local/etc/nginx/nginx.conf
```

And in the installation directory create a config (as the user running
the app):

```
cat << EOF > amusewikifarm_local.conf
<Model::Webserver>
nginx_root /usr/local/etc/nginx
</Model::Webserver>
EOF
```

Then rerun:

`carton exec script/amusewiki-generate-nginx-conf` and follow the
instructions again.

-- 
Marco

**Comment by Enrico68** [comment]
Following all the instructions : 

- the directories where already created
- I have added the line to the http stanza in nginx.conf 

`````
http {
 9     include       mime.types;
 8     default_type  application/octet-stream;
 7
 6     #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
 5     #                  '$status $body_bytes_sent "$http_referer" '
 4     #                  '"$http_user_agent" "$http_x_forwarded_for"';
 3
 2     #access_log  logs/access.log  main;
 1
 0     sendfile        on;
 1     #tcp_nopush     on;
 2
 3     #keepalive_timeout  0;
 4     keepalive_timeout  65;
 5
 6     #gzip  on;
 7
 8     server {
 9         listen       80;
10         server_name  oran.local;
11
12
13         #charset koi8-r;
14
15         #access_log  logs/host.access.log  main;
16
17         location /Users/enricopirani/ {
18             root   html;
19             index  index.html index.htm;
20             include /usr/local/etc/nginx/sites-enabled/*;
21         }
`````
 - created the script `amusewikifarm_local.conf` on the git directory `/Users/enricopirani/amusewiki` 
 - rerun the `carton exec script/amusewiki-generate-nginx-conf`


now when I run nginx got this error 

`nginx: [emerg] "server" directive is not allowed here in /usr/local/etc/nginx/sites-enabled/amusewiki:1`


and still the host `http://oran.local/admin/sites` oran.local ha rifiutato la connessione.

**Comment by melmothx** [comment]
Enrico Pirani ***@***.***> writes:

> `````
> http {
>  9     include       mime.types;
>  8     default_type  application/octet-stream;
>  7
>  6     #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
>  5     #                  '$status $body_bytes_sent "$http_referer" '
>  4     #                  '"$http_user_agent" "$http_x_forwarded_for"';
>  3
>  2     #access_log  logs/access.log  main;
>  1
>  0     sendfile        on;
>  1     #tcp_nopush     on;
>  2
>  3     #keepalive_timeout  0;
>  4     keepalive_timeout  65;
>  5
>  6     #gzip  on;
>  7
>  8     server {
>  9         listen       80;
> 10         server_name  oran.local;
> 11
> 12
> 13         #charset koi8-r;
> 14
> 15         #access_log  logs/host.access.log  main;
> 16
> 17         location /Users/enricopirani/ {
> 18             root   html;
> 19             index  index.html index.htm;
> 20             include /usr/local/etc/nginx/sites-enabled/*;
> 21         }
> `````
>  - created the script `amusewikifarm_local.conf` on the git directory `/Users/enricopirani/amusewiki` 
>  - rerun the `carton exec script/amusewiki-generate-nginx-conf`
>
>
> now when I run nginx got this error 
>
> `nginx: [emerg] "server" directive is not allowed here in /usr/local/etc/nginx/sites-enabled/amusewiki:1`


Please remove the whole `server { }` stanza I'm seeing there, which is
squatting the oran.local virtual host.

Then add the line:

include /usr/local/etc/nginx/sites-enabled/*;

right after `include servers/*;`, at the end of the `http { }` stanza.

-- 
Marco

**Comment by Enrico68** [comment]
[it works!](https://i.imgur.com/Zwbb9SY.pngl)
thanks !

Can I send you an update of installations step for OSX ? (if I remember everything :-))

**Comment by melmothx** [comment]
Nice! You're very welcome to open a pull request here: https://github.com/melmothx/amusewiki-site against https://github.com/melmothx/amusewiki-site/blob/master/i/il/install.muse it would be a nice addition. Thanks!

**Comment by Enrico68** [comment]
Sorry, Marco to bother you again. Still, I have a problem with the PDF production. I [cannot](https://imgur.com/GqIJmmG) see the PDF icons on top of the article.

**Comment by melmothx** [comment]
Enrico Pirani ***@***.***> writes:

> Sorry, Marco to bother you again. Still, I have a problem with the PDF
> production. I [cannot](https://imgur.com/GqIJmmG) see the PDF icons on
> top of the article.

Ok, some questions:

 - Are the PDF enabled at all? (User menu => Edit site configuration =>
   Formats or directly /settings/formats)
 - What happens if you rebuild a text? (last icon in the infobox)
 - Are there failing jobs in /admin/jobs/show?

Please note that the initial site comes with disabled PDF and enabling
them right away doesn't trigger a full rebuild. For that there is User
menu => Rebuild all generated files.

-- 
Marco

**Comment by Enrico68** [comment]
> - Are the PDF enabled at all? (User menu => Edit site configuration =>
   Formats or directly /settings/formats)

I have [enable](https://imgur.com/znNVSMu) it 

>  - What happens if you rebuild a text? (last icon in the infobox)

````
Job rebuild started at Sat Nov  6 21:33:49 2021
Working on amusewiki-for-sysadmins.muse file in ./repo/amw/a/af
* Created amusewiki-for-sysadmins.bare.html
* Created amusewiki-for-sysadmins.html
* Created amusewiki-for-sysadmins.epub
* Created amusewiki-for-sysadmins.tex
* Created amusewiki-for-sysadmins.zip
Scheduled generation of /library/amusewiki-for-sysadmins.pdf (Plain PDF) as task number #248
Scheduled generation of /library/amusewiki-for-sysadmins.a4.pdf (A4 imposed PDF) as task number #249
Scheduled generation of /library/amusewiki-for-sysadmins.lt.pdf (Letter imposed PDF) as task number #250
Slides (PDF) is not needed
Inserting data for ./repo/amw/a/af/amusewiki-for-sysadmins.muse
Updating amusewiki-for-sysadmins in Xapian db
Updating title and category sorting
Updated 0 records in 0 seconds
Scheduled static indexes generation
Job rebuild finished at Sat Nov  6 21:33:50 2021
`````
this is what I get for task number 248 

````
ob build_custom_format started at Sat Nov  6 21:33:51 2021
/var/folders/_z/k6c35fwj5k31fz2lg6mcrddc0000gn/T/PBwdijVeKr/amusewiki-for-sysadmins.muse is not a file at ./local/lib/perl5/Text/Amuse/Compile.pm line 606.
WARNINGS intercepted:
error: Could not extract /var/folders/_z/k6c35fwj5k31fz2lg6mcrddc0000gn/T/PBwdijVeKr safely: /var is an existing symbolic link 
 at lib/AmuseWikiFarm/Schema/Result/Job.pm line 811.
Job build_custom_format finished at Sat Nov  6 21:33:51 2021

/var/folders/_z/k6c35fwj5k31fz2lg6mcrddc0000gn/T/PBwdijVeKr/amusewiki-for-sysadmins.c3.pdf not produced!
````

>  Please note that the initial site comes with disabled PDF and enabling
them right away doesn't trigger a full rebuild. For that there is User
menu => Rebuild all generated files.

output of rebuilding all generated files 

````
rebuild completed
Number of jobs: 50/50
Failed: 0
Started: Saturday, November 6, 2021 at 8:36:39 PM UTC
Completed: Saturday, November 6, 2021 at 8:37:51 PM UTC
`````

**Comment by melmothx** [comment]
I believe you're hitting this problem here: https://www.perlmonks.org/?node_id=1228850

Please try to pull master (I've added a commit), restart the application with `./init-all.sh restart` and try again rebuilding one file.

**Comment by Enrico68** [comment]
tutto funziona perfettamente! 
ciao , grazie ancora !
