### ISSUE TITLE
Javascript on specific pages

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#391]
Is this a possible feature? There's no reason, just a question.

**Comment by melmothx** [comment]
Rojen Zaman ***@***.***> writes:

> Is this a possible feature? There's no reason, just a question.

Isn't the local.js enough for local hacks? Can't you just check the
window.location.pathname and act accordingly?

-- 
Marco

**Comment by rojenzaman** [comment]
Okie dokie. It is enough.
