### ISSUE TITLE
Special page redirection is wrong

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#394]
Here I have two special page named:
 - Test 1  (`test-1`)
 - Test 2 (`test-2`)

Once I want to delete and redirect `Test 1` to `Test 2`, I put `DELETED redirect: test-2` header to `Test 1`. Redirection works bu it points false URL like: `/speacials/test-2`. But is wrong, it would be: `/speacial/test-2`. The letter `s` is excess character here.

Here is live example: https://playwithamuse.rojenz.de/special/test-1/

```bash
$ curl https://playwithamuse.rojenz.de/special/test-1/
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Moved</title>
</head>
<body>
<p>This item has moved <a href="https://playwithamuse.rojenz.de/specials/test-2">here</a>.</p>
</body>
</html>

```

**Comment by melmothx** [comment]
Ok, this is addressed in master, but looking at this, probably even the code is wrong, and should a be a 301 Permanent instead. I can't recall the reason behind the 302, if any. Thoughts?

**Comment by rojenzaman** [comment]
Thank you. Yes I think it should be 301 permanent (redirection feature is already used for permanent redirects). I have no idea why is 302.
