### ISSUE TITLE
Importing POD documents

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#4]
Is this possible?

**Comment by melmothx** [comment]
"Stefan Hornburg (Racke)" <notifications@github.com> writes:

> Is this possible?

It would be nice and it's definitively possible. Let me keep this issue
open and look at it when I get a chance.

-- 
Marco

**Comment by racke** [comment]
:+1:

**Comment by melmothx** [comment]
Waiting for a new release of Pod::Simple::Wiki

**Comment by jmcnamara** [comment]
Latest version of Pod::Simple::Wiki with Muse support is now on CPAN (https://metacpan.org/release/JMCNAMARA/Pod-Simple-Wiki-0.19). 

Allow the usual 24 hours for it to propagate out to all the servers.

**Comment by melmothx** [comment]
@jmcnamara Thanks!
