### ISSUE TITLE
How to enable other categories? (publisher, series, location)

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#400]
It seems  publisher and location category types works on staging site: https://staging.amusewiki.org/library/different-topics-en
 - https://staging.amusewiki.org/category/location/ankara
 - https://staging.amusewiki.org/category/publisher/heretik

But they are not work my local instance, how to I enable it? I don't see any option for this in admin console.

I want to enable publisher, seriesname and location. Also it is possible to add another category type?

**Comment by melmothx** [comment]
There's a link below: "Fixed topic list" in the admin.

"Beside topics and authors you can add more categories here" => pointing to 
/settings/categories

Does it help?

**Comment by rojenzaman** [comment]
Sorry, I see now. It help.
