### ISSUE TITLE
Feed enclosures

### ISSUE THREAD

**Issue by melmothx** [melmothx/amusewiki#405]
The RSS  enclosure file type is epub, any chance to remove it or change it to PDF or specify what should or shouldn't be included? Here the line: https://github.com/melmothx/amusewiki/blob/df5585bc97ffc9eab069bdc4d9aedd5bad7a0d98/lib/AmuseWikiFarm/Schema/Result/Site.pm#L4763-#L4772

In OPDS the default file type was epub but I was able to fix this issue with nginx sub_filter: 

```nginx
sub_filter '.epub\" type=\"application/epub+zip\"' '.pdf\" type=\"application/pdf\"';
```

However, since length attribute always has different values, I can't replace the RSS enclosure file type with sub_filter.

Do you think this is a difficult or unnecessary feature? Would it be ok for you to adapt it to Amusewiki settings? Or should I create a new issue about it?

_Originally posted by @rojenzaman in https://github.com/melmothx/amusewiki/issues/404#issuecomment-1250387089_

**Comment by rojenzaman** [comment]
> @melmothx  There is some logic to hammer out. The epub was chosen because it's always generated. That's not the case with PDF (we have multiple ones). Even an attachment could be a candidate. So I think the request needs to be elaborated a bit. There could be a setting to choose between: "stock epub" (default), "highest priority generated file", "first attachment or highest priority generated file" something like that.

Sounds good, will this choice be in the site configuration? Also will this support OPDS as well?

**Comment by melmothx** [comment]
@rojenzaman please give a try to this branch, thanks!

**Comment by melmothx** [comment]
Branch is `405-feed-enclosures`

**Comment by rojenzaman** [comment]
Thank you, works like a charm!

One more thing: After changing the "Feed enclosure method" option, the rss file was not affected until I deleted it locally (`site_files/rss.xml`). Can you provide a reindex function to the rss.xml file or make it more dynamic? It will be useful for users who do not have access to the local repo. (After adding a new post it gets fixed, but I have considered the scenario of not adding a post.)

**Comment by melmothx** [comment]
That's done. Any other comment or we're good here?

**Comment by rojenzaman** [comment]
We are good, can you merge tr i18n PR to avoid .po collision with new strings?
