### ISSUE TITLE
Special pages are still in the RSS feed even the publication date is too old

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#408]
Publication date of special pages for RSS feed corrected here #404, but now we have a small problem that I noticed: Special pages are still in the RSS feed, even though the publication date is very old. Some RSS aggregators ignore the publication date and process the latest X post, that's why old special pages appear.

Can you remove special pages with old publication date from RSS feed to overcome this issue?

**Comment by rojenzaman** [comment]
If you're going to play with the code, can you also give a div id to this block?

>  Keep in mind that I’m cleaning the text and give it back to you in the markup used on this site. It’s up to you to check it and finally upload it. Some rarely used markup will be lost in the process. Please check the preview on the next step, where you can also insert images. 


![Screenshot from 2022-10-08 22-59-57](https://user-images.githubusercontent.com/46978479/194725830-a4774478-7967-49a2-87f1-c7abd52ae360.png)

**Comment by melmothx** [comment]
@rojenzaman  Please give a try to `rss-feed-special-no-special-408` and let me know. Thanks!

**Comment by rojenzaman** [comment]
Thank you so much, it's fixed!
