### ISSUE TITLE
Correct way to add texlive to PATH

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#411]
I installed both: **amusewiki-texlive/20220322-1** and **./script/install-texlive.sh**.

Depending on the installation method I added them to the path:
`/opt/amusewiki-texlive/current/bin/arch`
`/var/lib/amusewiki/local/texlive/2022/bin/x86_64-linux`

Then I ran `./install.sh` and completed every steps that described here: https://amusewiki.org/library/install#toc1

**install.sh** says texlive is ok:
```bash
Checking installation of TeX live: OK
```

**muse-compile.pl --pdf test.muse** successfully generates pdf file:
```
Using Text::Amuse 1.82, Text::Amuse::Compiler 1.87, PDF::Imposition 0.26
Working on test.muse file in /var/lib/amusewiki/repo/amw/t/tt
sans font not found, using the default
mono font not found, using the default
main font not found, using the default
* Created test.tex
* Created test.pdf
```

But wiki says xelatex not found in path:

```
Job build_custom_format started at Sun Oct 16 20:18:05 2022
Working on test.muse file in /tmp/BHHILNUWtk
* Created test.tex
Command 'xelatex' not found in ./local/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin at ./local/lib/perl5/Text/Amuse/Compile/File.pm line 850.
Job build_custom_format finished at Sun Oct 16 20:18:06 2022
```
Why did this happen? Is there a way to tell the wiki where texlive is?

**Comment by melmothx** [comment]
Rojen Zaman ***@***.***> writes:

> I installed both: **amusewiki-texlive/20220322-1** and **./script/install-texlive.sh**.
>
> Depending on the installation method I added them to the path:
> `/opt/amusewiki-texlive/current/bin/arch`
> `/var/lib/amusewiki/local/texlive/2022/bin/x86_64-linux`
>
> Then I ran `./install.sh` and completed every steps that described here: https://amusewiki.org/library/install#toc3run
>
> **install.sh** says texlive is ok:
> ```bash
> Checking installation of TeX live: OK
> ```
>
> **muse-compile.pl --pdf test.muse** successfully generates pdf file:
> ```
> Using Text::Amuse 1.82, Text::Amuse::Compiler 1.87, PDF::Imposition 0.26
> Working on test.muse file in /var/lib/amusewiki/repo/amw/t/tt
> sans font not found, using the default
> mono font not found, using the default
> main font not found, using the default
> * Created test.tex
> * Created test.pdf
> ```
>
> But wiki says xelatex not found in path:
>
> ```
> Job build_custom_format started at Sun Oct 16 20:18:05 2022
> Working on test.muse file in /tmp/BHHILNUWtk
> * Created test.tex
> Command 'xelatex' not found in ./local/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin at ./local/lib/perl5/Text/Amuse/Compile/File.pm line 850.
> Job build_custom_format finished at Sun Oct 16 20:18:06 2022
> ```
> Why did this happen? Is there a way to tell the wiki where texlive is?

It depends where the jobber is started. Assuming it starts from the the
systemd service you need this:

Environment="PATH=/opt/amusewiki-texlive/current/bin/arch:/usr/local/bin:/usr/bin:/bin"
ExecStart=/usr/bin/amusewiki-jobber

The `generate-systemd-unit-files` scripts should inherit the current
PATH, hence producing "good" services.

If you start the jobber with ./init-all.sh you should already be good,
if the PATH is correctly set.

In your case I think you skipped something, or used another shell
without the correct path.

-- 
Marco
