### ISSUE TITLE
"Generate Index" selected as no but listed in OPDS and sitemap.txt (custom directive)

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#412]
"Active" and "Generate Index" box set to no for a custom directive, but still listed in the sitemap.txt file.

"Generate Index" box set to no for a custom directive, but still listed in the OPDS.

**Comment by rojenzaman** [comment]
@melmothx I guess the unindexed categories should be excluded from the **/console/categories/list** page, can you check? I've just realized.

**Comment by melmothx** [comment]
Yes, correct, done, thanks!
