### ISSUE TITLE
New text notification

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#413]
Mail test works.
Mail for "Password reset" works.
Mail for "new user creation information" works.

I set `EMAIL_SENDER_TRANSPORT_sasl_password`, `EMAIL_SENDER_TRANSPORT`, `EMAIL_SENDER_TRANSPORT_host`, `EMAIL_SENDER_TRANSPORT_ssl`, `EMAIL_SENDER_TRANSPORT_sasl_username`, `EMAIL_SENDER_TRANSPORT_port` variables correctly.

But new text notification not works.

How can I send the following mail to users? As I recall, the template was:
```
Changes for New Text
https://amusewiki.localdomain/library/new-text

This text is new.

The revision has the following messages



 * 2022-10-20T00:00:01

new text


-- testuser



If the user provided a mail, it's listed in the mail's CC field

To resume the editing you can visit the following URL:

https://amusewiki.localdomain/action/text/edit/new-text/<ID>

To view the changes introduced, you can visit the following URL:

https://amusewiki.localdomain/action/text/edit/new-text/<ID>/diff

Preview:

https://amusewiki.localdomain/action/text/edit/new-text/<ID>/preview

To apply the changes, you can visit https://amusewiki.localdomain/publish/pending
```

**Comment by melmothx** [comment]
Rojen Zaman ***@***.***> writes:

> Mail test works.
> Mail for "Password reset" works.
> Mail for "new user creation information" works.
> I set `EMAIL_SENDER_TRANSPORT_sasl_password`, `EMAIL_SENDER_TRANSPORT`, `EMAIL_SENDER_TRANSPORT_host`, `EMAIL_SENDER_TRANSPORT_ssl`, `EMAIL_SENDER_TRANSPORT_sasl_username`, `EMAIL_SENDER_TRANSPORT_port` variables correctly.
>
> But new text notification not works.

Do you have the "Notify mail: blank field will disable them (comma
separated list)" and "Site mail (From field)" set in the site admin?

-- 
Marco

**Comment by rojenzaman** [comment]
I set "Site mail", but ""Notify mail" is blank.

**Comment by rojenzaman** [comment]
Thanks, I set "Notify mail" and its worked.
