### ISSUE TITLE
mirror/index.html does not load any content if there is an error in local.js

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#415]
Static mirror page not load any content when local.js has an error.

For example:
 - https://theanarchistlibrary.org/mirror/index.html
 - https://tr.anarchistlibraries.net/mirror/index.html

Related JavaScript error for [theanarchistlibrary.org](https://theanarchistlibrary.org/mirror/index.html) is:

```
Uncaught TypeError: document.querySelector(...) is null
    <anonymous> https://theanarchistlibrary.org/mirror/site_files/local.js:51
``` 

It can load content when the error is fixed.

**Comment by melmothx** [comment]
Well, there's nothing I can do here, beside recommending to notify them about the breakage. The mirror page is huge and deferring the table rendering to the client was the only way to keep it functional.

Incidentally, that "dark mode" js is a hack and the "alternate theme" where you can use a dark one is already supported natively (check the admin page), so those sites break without any real reason.

**Comment by rojenzaman** [comment]
Okay, they need to be notified on this breakage.
