### ISSUE TITLE
mirror/index.html enclosures

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#416]
Hi, can you provide the attachments to mirror page, is this possible? 

I think the attachment can be listed on "Files" column. Also, if an item in the "Title" column has an attachment, a link pointing to the attachment can be left instead of a link pointing to the html page.

Thank you.

**Comment by melmothx** [comment]
@rojenzaman please give it a try to `static-index-enclosures-416` and let me know.

Thanks

**Comment by rojenzaman** [comment]
Thank you, can you give div id to file icons?

**Comment by rojenzaman** [comment]
Does the "Estimated pages" value come from a global variable? I see this value on the `/search` page with the "Number of pages" fieldset and on the listing pages with `amw-show-text-type-and-number-of-pages` box. If these values come from a global variable, is there a way to set this variable to the page count of first attachment file? There is one more thing I would like to point out about this situation, if possible.

**Comment by melmothx** [comment]
> Thank you, can you give div id to file icons?

I gave a format-specific class to each icon, I can't give them an id, as they are not unique across the page, but I guess this is what you meant?

**Comment by melmothx** [comment]
> Does the "Estimated pages" value come from a global variable? I see this value on the `/search` page with the "Number of pages" fieldset and on the listing pages with `amw-show-text-type-and-number-of-pages` box. If these values come from a global variable, is there a way to set this variable to the page count of first attachment file? There is one more thing I would like to point out about this situation, if possible.

I think this should be another issue, but:

 - the number of pages come from the rendered HTML. Number of characters / 2000, which should be sensible.
 - The book/article is give by the presence of `*` and `**` sections (parts and chapters)
 - I think I can't count characters on attachments, they're binary files (usually).

So the display of that column and icon depends on the site setting, like the rest of the site.

**Comment by rojenzaman** [comment]
> I gave a format-specific class to each icon, I can't give them an id, as they are not unique across the page, but I guess this is what you meant?

Yes it was. Thank you

**Comment by rojenzaman** [comment]
> I made a change, so the display of that column and icon depends on the site setting now, like the rest of the site.

OK. The display depending on the setting was exactly what I expected, so things don't get complicated here. I think this setting is enough. Thanks!
