### ISSUE TITLE
Enforce user to save email

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#417]
Hi, can you provide "enforce save email address" option before publishing text, like "enforce save message " and "enforce user to choose the URI" options? I think it will be effective for staying in touch with external users. Is this possible?

Thank you.

**Comment by melmothx** [comment]
Please try out the branch `enforce-email-417`

**Comment by rojenzaman** [comment]
Thank you. I've tried, there is no problem.

Probably the text "Enforce e-mail on submission" will be localized in soon, right?

**Comment by melmothx** [comment]
Sure, here we go.
