### ISSUE TITLE
local-alt.css for alternate theme

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#419]
**local-alt.css** mechanism must be provided to make local changes to the alternate theme. In addition, **navlogo-alt.png** mechanism  must be provided to give a custom logo to the alternate theme. So, admins can make local changes on the alternate theme.

Currently, local changes for alternate theme can be made by various Javascript methods, but the problem with them is that there is a flashing problem during page loading. Also local changes can be made by adding new theme to the amusewiki codebase, but the problem here is that not everyone has access to the codebase in large projects.

**Comment by melmothx** [comment]
@rojenzaman please give it a try to `alt-local-files-419`

**Comment by rojenzaman** [comment]
I've tried, works like a charm. Thanks!
