### ISSUE TITLE
BAIL_OUT when xelatex is not found?

### ISSUE THREAD

**Issue by guest20** [melmothx/amusewiki#424]
should this `die` be a `BAIL_OUT ` ?
https://github.com/melmothx/amusewiki/blob/9e05dacf6621b511fae8b80afad056ee5175bbfa/t/00-prepare-tests.t#L28

Quoth [Test::More](https://metacpan.org/pod/Test::More#BAIL_OUT):
> BAIL_OUT($reason);
> Indicates to the harness that things are going so badly all testing should terminate. This includes the running of any additional test scripts.
> This is typically used when testing cannot continue such as a critical module failing to compile or a necessary external utility not being available such as a database connection failing.

Right now this `die` in `00-prepare-tests.t` skips creating the test db, because a critical tool is missing. When that happens the tests continue, but any time they talk to the database they `die`. 

To me this sounds like an ideal place for a `BAIL_OUT`

**Comment by melmothx** [comment]
Yes indeed. Thanks for the report.
