### ISSUE TITLE
 Which fonts do I need to run the tests? 

### ISSUE THREAD

**Issue by guest20** [melmothx/amusewiki#425]
I'm not exactly sure how these packages and the tests fit together, but it seem like `t/00-prepare-tests.t` doesn't pass without `fonts-linuxlibertine` installed.

https://github.com/melmothx/amusewiki/blob/6e2d073f669e32a9af57ff0c784d8416f4900ed6/t/00-prepare-tests.t#L132
and if this font isn't installed, this test fails: 
https://github.com/melmothx/amusewiki/blob/6e2d073f669e32a9af57ff0c784d8416f4900ed6/t/00-prepare-tests.t#L184

https://amusewiki.org/library/custom-fonts

it seems like the tests want `fonts-dejavu-extra fonts-dejavu-core fonts-linuxlibertine`, so maybe they should also be in `Build-Depends-Indep`?

**Comment by melmothx** [comment]
guest20 ***@***.***> writes:

> I'm not exactly sure how these packages and the tests fit together, but it seem like `t/00-prepare-tests.t` doesn't pass without `fonts-linuxlibertine` installed.
>
> https://github.com/melmothx/amusewiki/blob/6e2d073f669e32a9af57ff0c784d8416f4900ed6/t/00-prepare-tests.t#L132
> and if this font isn't installed, this test fails: 
> https://github.com/melmothx/amusewiki/blob/6e2d073f669e32a9af57ff0c784d8416f4900ed6/t/00-prepare-tests.t#L184
>
> https://amusewiki.org/library/custom-fonts
>
> it seems like the tests want `fonts-dejavu-extra fonts-dejavu-core fonts-linuxlibertine`, so maybe they should also be in `Build-Depends-Indep`?

Hm, I'm pretty sure that those are supposed to be pulled from
libtext-amuse-compile-perl, which has all the needed fonts listed in the
deps. Do you have libtext-amuse-compile-perl installed?

-- 
Marco
