### ISSUE TITLE
Feature request: Tritary footnotes for hyperlinks for PDFs only

### ISSUE THREAD

**Issue by ienzo** [melmothx/amusewiki#447]
Some people submit articles that have links in it but looks awkward in the PDF for printing. It will look like this:

> See this link here for more. 

That’s how it will look like when you print it. It’s awkward and weird. A reader of a zine would be like “what link??” I propose a tritary footnote system only visible on PDFs to accommodate these links. It would look like:

> See this link here* for more.
> _____________
> \* https://hello.com

Why PDFs only? Because EPUBs and the normal web view can support hyperlinks.

**Comment by melmothx** [comment]
ienzo ***@***.***> writes:

> Some people submit articles that have links in it but looks awkward in the PDF for printing. It will look like this:
>
>> See this link here for more. 

Such text usually comes from blog posts and/or online articles which
were meant to be read online, not to be printed.

> That’s how it will look like when you print it. It’s awkward and
> weird. A reader of a zine would be like “what link??” I propose a
> tritary footnote system only visible on PDFs to accommodate these
> links. It would look like:
>
>> See this link here* for more.
>> _____________
>> \* https://hello.com
>
> Why PDFs only? Because EPUBs and the normal web view can support hyperlinks. 

What stops you or your submitter to make the link explicit with a real
footnote?

I would accept a patch to the preprocessor to turn such links into
explict ones.

https://github.com/melmothx/text-amuse-preprocessor

Honestly I don't like the idea of adding (after more of a decade) a
feature without a clear gain and without a clear motivation, beside the
laziness of the editor.

Even the secondary footnotes are less robust then it's desired, go
figure a third set.

-- 
Marco

**Comment by ienzo** [comment]
Alright then. I’ll be fine with you closing this issue then.
