### ISSUE TITLE
instance debian bookworm upgrade issues

### ISSUE THREAD

**Issue by rocinanteee** [melmothx/amusewiki#449]
Since upgrading the Debian to Bookworm, our instance has encountered various issues:

When attempting to publish a text in the pending queue:
```

Status: failed

Job publish started at Wed Dec  6 22:24:10 2023
Job publish finished at Wed Dec  6 22:24:11 2023

Original html found, but target exists at /usr/share/perl5/AmuseWikiFarm/Schema/Result/Revision.pm line 865.
```
And then when adding a brand new text to the pending queue and attempting to publish:

```
Status: failed

Job publish started at Wed Dec  6 22:40:21 2023
Working on test-1234-test-1234.muse file in ./repo/en/t/t1
isa check for "file" failed: /usr/share/fonts/truetype/karla/Karla-Regular.ttf is not a font file at /usr/share/perl5/Text/Amuse/Compile/Fonts/File.pm line 64.
Inserting data for ./repo/en/t/t1/test-1234-test-1234.muse
Changing test-1234-test-1234 status from editing to published
Job publish finished at Wed Dec  6 22:40:49 2023

</var/lib/amusewiki/repo/en/t/t1/test-1234-test-1234.status> not found!
```

And finally, when I go to "full site configuration" in the user dropdown menu, I'm met with the following message:

> (en) Please come back later
> (fr) SVP veuillez revenir plus tard
> (de) Bitte versuchen sie es spaeter nocheinmal
> (at) Konnten's bitt'schoen spaeter nochmal reinschauen
> (no) Vennligst prov igjen senere
> (dk) Venligst prov igen senere
> (pl) Prosze sprobowac pozniej
> (pt) Por favor volte mais tarde
> (ru) Попробуйте еще раз позже
> (ua) Спробуйте ще раз пізніше
> (it) Per favore riprova più tardi

**Comment by melmothx** [comment]
rocinanteee ***@***.***> writes:

> Since upgrading the Debian to Bookworm, our instance has encountered various issues:

That's likely due to the font paths changed during the upgrade by system
packages.

So correct the file here: /etc/amusewiki.d/fontspec.json removing the
offending files (the errors you reporting is showing those paths).

So remove the whole Karla block, e.g.

   {
      "bold" : "/usr/share/fonts/truetype/karla/Karla-Bold.ttf",
      "bolditalic" : "/usr/share/fonts/truetype/karla/Karla-BoldItalic.ttf",
      "desc" : "Karla",
      "italic" : "/usr/share/fonts/truetype/karla/Karla-Italic.ttf",
      "name" : "Karla",
      "regular" : "/usr/share/fonts/truetype/karla/Karla-Regular.ttf",
      "type" : "sans"
   },

and if you have Charis, update those paths as well, or remove the whole
block if you don't use it.

Then check back the logs and see if you have other failing paths.

Please check if you have other site specific fontspec.json files:

ls /var/lib/amusewiki/repo/*/site_files/fontspec.json

-- 
Marco

**Comment by melmothx** [comment]
Depending on your instance, you may have a `/var/lib/amusewiki/fontspec.json` file instead of a symlink to `/etc/amusewiki.d/fontspec.json`. Bottom line, you need all the `fontspec.json` files valid.

**Comment by melmothx** [comment]
https://amusewiki.org/library/custom-fonts

**Comment by rocinanteee** [comment]
all set, thanks!
