### ISSUE TITLE
[Feature request] New filter: Bump #pubdate 

### ISSUE THREAD

**Issue by ienzo** [melmothx/amusewiki#450]
For varying reasons, texts often remain at the queue for a while. As an ad hoc method of making sure old items in queue appear on the top of the new texts page, the `#pubdate` line in the preamble is deleted. Down the line, however, this makes the text appear to the top of the new texts page whenever it is edited, which it can be years after the fact. 

What I request is a new filter, probably called `Bump #pubdate`  that, when checked, updates the pubdate to the time of next commit when the `Save` button is pressed. That way, we no longer need to use ad hoc methods and hacks of old texts in queue to appear to the start of the new texts page.

**Comment by melmothx** [comment]
Please give it a try on https://staging.amusewiki.org/ and see if that's what you needed.

**Comment by ienzo** [comment]
It looks great! Thanks for this. A small question, would the inclusion of
microseconds be a problem for the engine? I notice after seconds it also
records what seem to be microseconds.

**Comment by melmothx** [comment]
ienzo ***@***.***> writes:

> It looks great! Thanks for this. A small question, would the inclusion of
> microseconds be a problem for the engine? I notice after seconds it also
> records what seem to be microseconds.

It should be pretty safe, but I'll throw in a test case and release
this.

Debian package should be available later today.

-- 
Marco
