### ISSUE TITLE
Download the whole Wiki

### ISSUE THREAD

**Issue by avidseeker** [melmothx/amusewiki#458]
Wikis are often projects with enormous amounts of volunteer efforts are put into.

Contributors should be able to download their collective work instead of trusting the Wiki owner with their work.

**Comment by melmothx** [comment]
And the actual issue is...? Please see:

https://amusewiki.org/git

https://amusewiki.org/mirror/index.html

https://amusewiki.org/robots.txt

https://amusewiki.org/library/mirroring

Closing this.
